### PR TITLE
Fix a text parser assertion on bad immediates

### LINKED ISSUE #7251: "expected end of instruction" text parse error on invalid memory index
```wat
 (memory 1 1)

 (func $v128.load16_lane1 (param $0 i32) (param $1 v128) (result v128)
  (v128.load16_lane 1 0 ;; invalid memory index
   (local.get $0)
   (local.get $1)
  )
 )
```
```
$ bin/wasm-opt a.wat 
wasm-opt: src/parser/parsers.h:1008: MaybeResult<> wasm::WATParser::foldedinstr(Ctx &) [Ctx = wasm::WATParser::ParseDefsCtx]: Assertion `ctx.in.getPos() == *info.end && "expected end of instruction"' failed.
Aborted
```

### PR DESCRIPTION
**Pull request by tlively**
We previously asserted that the end of a nested expression is the same
when we parse it with a null context just to find its children and when
we parse it for real. It turns out that it is possible for the two end
positions to be different when the instruction is invalid in a way that
only the real parse catches. Return a normal error instead of asserting
because it is possible for invalid input to trigger this condition.

Fixes #7251.

### CODE REVIEW

File: src/parser/parsers.h [hunk 1]
```diff
@@ -1005,6 +1005,13 @@ template<typename Ctx> MaybeResult<> foldedinstr(Ctx& ctx) {
...
       assert(inst && "unexpectedly failed to parse instruction");
       CHECK_ERR(inst);
+      // We have already parsed the instruction, so we generally know where it
+      // ends. But there may have been some invalid extra immediates (e.g.
+      // invalid memory indices) that we only realize are invalid now that we've
+      // parsed the instruction for real.
+      if (ctx.in.getPos() != *info.end) {
+        return ctx.in.err("expected end of instruction");
+      }
       assert(ctx.in.getPos() == *info.end && "expected end of instruction");
```
Comment (kripken) [inline src/parser/parsers.h:1015]: Can remove this assertion now.

**Review by kripken — APPROVED** [review]

File: src/parser/parsers.h (hunk 1 above)
Comment (tlively) [reply src/parser/parsers.h:1015]: Oops!
