### PR TITLE
Stop using operator[] only for default-insertion into maps

### LINKED ISSUE #8124: binaryen failing to build with llvm tip-of-tree
For the last few days our llvm roller has been failing due to binaryen not building.

For example this is the first failing build: https://chromium-review.googlesource.com/c/emscripten-releases/+/7256569.

Looks like something to do with the nodicard attribute/warning:

```
/b/s/w/ir/cache/builder/v8/buildtools/reclient/rewrapper -cfg=/b/s/w/ir/cache/builder/v8/buildtools/reclient_cfgs/chromium-browser-clang/rewrapper_linux.cfg /b/s/w/ir/cache/builder/v8/third_party/llvm-build/Release+Asserts/bin/clang++ --sysroot=/b/s/w/ir/cache/builder/emscripten-releases/sysroot_debian_stretch_amd64_v2 -Dbinaryen_EXPORTS -I/b/s/w/ir/cache/builder/emscripten-releases/binaryen/src -I/b/s/w/ir/cache/builder/emscripten-releases/build/binaryen-out -I/b/s/w/ir/cache/builder/emscripten-releases/binaryen/third_party/mimalloc/include -isystem /b/s/w/ir/cache/builder/emscripten-releases/binaryen/third_party/FP16/include -isystem /b/s/w/ir/cache/builder/emscripten-releases/binaryen/third_party/llvm-project/include -stdlib++-isystem/b/s/w/ir/cache/builder/emscripten-releases/build/temp/libcxx-install/include/c++/v1 -no-canonical-prefixes -fno-omit-frame-pointer -fno-rtti -fPIC -fcolor-diagnostics -DBUILD_LLVM_DWARF -Wall -Werror -Wextra -Wno-unused-parameter -Wno-dangling-pointer -Wno-implicit-int-float-conversion -Wno-unknown-warning-option -Wswitch -Wimplicit-fallthrough -Wnon-virtual-dtor -Wctad-maybe-unsupported -Wno-deprecated-declarations -O3 -DNDEBUG -UNDEBUG -fPIC -pthread -std=c++17 -MD -MT CMakeFiles/binaryen.dir/src/ir/table-utils.cpp.o -MF CMakeFiles/binaryen.dir/src/ir/table-utils.cpp.o.d -o CMakeFiles/binaryen.dir/src/ir/table-utils.cpp.o -c /b/s/w/ir/cache/builder/emscripten-releases/binaryen/src/ir/table-utils.cpp
In file included from /b/s/w/ir/cache/builder/emscripten-releases/binaryen/src/ir/table-utils.cpp:17:
In file included from /b/s/w/ir/cache/builder/emscripten-releases/binaryen/src/ir/table-utils.h:22:
/b/s/w/ir/cache/builder/emscripten-releases/binaryen/src/ir/module-utils.h:287:7: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
  287 |       map[func.get()];
      |       ^~~~~~~~~~~~~~~
/b/s/w/ir/cache/builder/emscripten-releases/binaryen/src/ir/table-utils.cpp:39:48: note: in instantiation of member function 'wasm::ModuleUtils::ParallelFunctionAnalysis<std::unordered_set<wasm::Name>>::ParallelFunctionAnalysis' requested here
   39 |   ModuleUtils::ParallelFunctionAnalysis<Names> analysis(
      |                                                ^
1 error generated.
```

This could of course be an llvm regression.

### PR DESCRIPTION
**Pull request by dschuff**
Upstream libc++ recently added the [[nodiscard]] attribute to the return value
of operator[] on maps, meaning the compiler now warns on uses of this operator
that only want to insert rather than also use the result.

Switch to using try_emplace, which does not construct the value unless insertion
succeeds, and is IMO more readable than operator[] for this purpose.

Fixes #8124

### CODE REVIEW

File: src/ir/module-utils.h [hunk 1]
```diff
@@ -284,7 +284,7 @@ struct ParallelFunctionAnalysis {
     // Fill in the map as we operate on it in parallel (each function to its own
     // entry).
     for (auto& func : wasm.functions) {
-      map[func.get()];
+      map.insert({func.get(), {}});
```
Comment (tlively) [inline src/ir/module-utils.h:287]: Why `insert` instead of `try_emplace` here?

**Review by tlively — COMMENTED** [review]
Can we add this warning on CI to avoid regressions?

File: src/ir/module-utils.h (hunk 1 above)
Comment (dschuff) [reply src/ir/module-utils.h:287]: Ah right I wanted to mention that. It's because `map` is actually an instance of `wasm::InsertOrderedMap`, (https://github.com/WebAssembly/binaryen/blob/main/src/support/insert_ordered.h#L92) and doesn't have try_emplace. So the other option would be to just fix that instead.

**Comment by dschuff** [comment]
> Can we add this warning on CI to avoid regressions?

I don't think we can without using the bleeding-edge libc++ because the [[nodiscard]] attribute isn't there before then, so there's nothing to warn about. I wouldn't actually be surprised if the change ends up getting backed out because it catches a lot of this code (there's already discussion on the relevant PR, see the link in the bug). But this still seems like a readability improvement.

File: src/passes/Inlining.cpp [hunk 2]
```diff
@@ -1344,7 +1344,7 @@ struct Inlining : public Pass {
     // fill in info, as we operate on it in parallel (each function to its own
     // entry)
     for (auto& func : module->functions) {
-      infos[func->name];
+      infos.try_emplace(func->name);
```
Comment (kripken) [inline src/passes/Inlining.cpp:1347]: These will definitely insert (the map is empty before), so perhaps `emplace` would be faster than `try_emplace`..? I admit I don't know if this would matter though.

The same might happen in a few other places, but this one is especially clear-cut (we clear the map right before the loop).

Comment (dschuff) [reply src/passes/Inlining.cpp:1347]: Yeah, I thought about that. The other difference between `emplace` and `try_emplace` is that the value is [constructed](https://en.cppreference.com/w/cpp/container/map/try_emplace.html) with `std::piecewise_construct`, and that actually matters, for reasons I don't 100% understand. For example, this spot. Here's the error if you try to use emplace here:

```
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/new_allocator.h:191:23: error: no matching constructor for initialization of 'std::pair<const wasm::Name, wasm::(anonymous namespace)::FunctionInfo>'
[build]   191 |         { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
[build]       |                              ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/alloc_traits.h:575:8: note: in instantiation of function template specialization 'std::__new_allocator<std::__detail::_Hash_node<std::pair<const wasm::Name, wasm::(anonymous namespace)::FunctionInfo>, true>>::construct<std::pair<const wasm::Name, wasm::(anonymous namespace)::FunctionInfo>, wasm::Name &>' requested here
[build]   575 |           __a.construct(__p, std::forward<_Args>(__args)...);
[build]       |               ^
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/hashtable_policy.h:2030:27: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<std::__detail::_Hash_node<std::pair<const wasm::Name, wasm::(anonymous namespace)::FunctionInfo>, true>>>::construct<std::pair<const wasm::Name, wasm::(anonymous namespace)::FunctionInfo>, wasm::Name &>' requested here
[build]  2030 |             __node_alloc_traits::construct(__alloc, __n->_M_valptr(),
[build]       |                                  ^
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/hashtable.h:312:19: note: in instantiation of function template specialization 'std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<const wasm::Name, wasm::(anonymous namespace)::FunctionInfo>, true>>>::_M_allocate_node<wasm::Name &>' requested here
[build]   312 |             _M_node(__h->_M_allocate_node(std::forward<_Args>(__args)...))
[build]       |                          ^
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/hashtable.h:2147:15: note: in instantiation of function template specialization 'std::_Hashtable<wasm::Name, std::pair<const wasm::Name, wasm::(anonymous namespace)::FunctionInfo>, std::allocator<std::pair<const wasm::Name, wasm::(anonymous namespace)::FunctionInfo>>, std::__detail::_Select1st, std::equal_to<wasm::Name>, std::hash<wasm::Name>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>>::_Scoped_node::_Scoped_node<wasm::Name &>' requested here
[build]  2147 |         _Scoped_node __node { this, std::forward<_Args>(__args)...  };
[build]       |                      ^
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/hashtable.h:1004:11: note: in instantiation of function template specialization 'std::_Hashtable<wasm::Name, std::pair<const wasm::Name, wasm::(anonymous namespace)::FunctionInfo>, std::allocator<std::pair<const wasm::Name, wasm::(anonymous namespace)::FunctionInfo>>, std::__detail::_Select1st, std::equal_to<wasm::Name>, std::hash<wasm::Name>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>>::_M_emplace<wasm::Name &>' requested here
[build]  1004 |         { return _M_emplace(__unique_keys{}, std::forward<_Args>(__args)...); }
[build]       |                  ^
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/unordered_map.h:396:16: note: in instantiation of function template specialization 'std::_Hashtable<wasm::Name, std::pair<const wasm::Name, wasm::(anonymous namespace)::FunctionInfo>, std::allocator<std::pair<const wasm::Name, wasm::(anonymous namespace)::FunctionInfo>>, std::__detail::_Select1st, std::equal_to<wasm::Name>, std::hash<wasm::Name>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>>::emplace<wasm::Name &>' requested here
[build]   396 |         { return _M_h.emplace(std::forward<_Args>(__args)...); }
[build]       |                       ^
[build] /usr/local/google/home/dschuff/s/emr/emscripten-releases/binaryen/src/passes/Inlining.cpp:1347:13: note: in instantiation of function template specialization 'std::unordered_map<wasm::Name, wasm::(anonymous namespace)::FunctionInfo>::emplace<wasm::Name &>' requested here
[build]  1347 |       infos.emplace(func->name);
[build]       |             ^
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_pair.h:294:17: note: candidate constructor not viable: no known conversion from 'wasm::Name' to 'const pair<const Name, FunctionInfo>' for 1st argument
[build]   294 |       constexpr pair(const pair&) = default;    ///< Copy constructor
[build]       |                 ^    ~~~~~~~~~~~
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_pair.h:779:12: note: candidate template ignored: could not match 'pair<_U1, _U2>' against 'wasm::Name'
[build]   779 |         constexpr pair(const pair<_U1, _U2>& __p)
[build]       |                   ^
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_pair.h:789:21: note: candidate template ignored: could not match 'pair<_U1, _U2>' against 'wasm::Name'
[build]   789 |         explicit constexpr pair(const pair<_U1, _U2>& __p)
[build]       |                            ^
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_pair.h:902:12: note: candidate template ignored: could not match 'pair<_U1, _U2>' against 'wasm::Name'
[build]   902 |         constexpr pair(pair<_U1, _U2>&& __p)
[build]       |                   ^
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_pair.h:913:21: note: candidate template ignored: could not match 'pair<_U1, _U2>' against 'wasm::Name'
[build]   913 |         explicit constexpr pair(pair<_U1, _U2>&& __p)
[build]       |                            ^
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_pair.h:725:17: note: candidate constructor template not viable: requires 0 arguments, but 1 was provided
[build]   725 |       constexpr pair()
[build]       |                 ^
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_pair.h:737:26: note: candidate constructor template not viable: requires 0 arguments, but 1 was provided
[build]   737 |       explicit constexpr pair()
[build]       |                          ^
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_pair.h:752:17: note: candidate constructor template not viable: requires 2 arguments, but 1 was provided
[build]   752 |       constexpr pair(const _T1& __a, const _T2& __b)
[build]       |                 ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_pair.h:762:26: note: candidate constructor template not viable: requires 2 arguments, but 1 was provided
[build]   762 |       explicit constexpr pair(const _T1& __a, const _T2& __b)
[build]       |                          ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_pair.h:830:2: note: candidate constructor template not viable: requires at least 2 arguments, but 1 was provided
[build]   830 |         pair(_U1&& __x, __zero_as_null_pointer_constant, ...)
[build]       |         ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_pair.h:843:2: note: candidate constructor template not viable: requires at least 2 arguments, but 1 was provided
[build]   843 |         pair(_U1&& __x, __zero_as_null_pointer_constant, ...)
[build]       |         ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_pair.h:856:2: note: candidate constructor template not viable: requires at least 2 arguments, but 1 was provided
[build]   856 |         pair(__zero_as_null_pointer_constant, _U2&& __y, ...)
[build]       |         ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_pair.h:869:2: note: candidate constructor template not viable: requires at least 2 arguments, but 1 was provided
[build]   869 |         pair(__zero_as_null_pointer_constant, _U2&& __y, ...)
[build]       |         ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_pair.h:881:12: note: candidate constructor template not viable: requires 2 arguments, but 1 was provided
[build]   881 |         constexpr pair(_U1&& __x, _U2&& __y)
[build]       |                   ^    ~~~~~~~~~~~~~~~~~~~~
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_pair.h:891:21: note: candidate constructor template not viable: requires 2 arguments, but 1 was provided
[build]   891 |         explicit constexpr pair(_U1&& __x, _U2&& __y)
[build]       |                            ^    ~~~~~~~~~~~~~~~~~~~~
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_pair.h:299:2: note: candidate constructor template not viable: requires 3 arguments, but 1 was provided
[build]   299 |         pair(piecewise_construct_t, tuple<_Args1...>, tuple<_Args2...>);
[build]       |         ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_pair.h:335:2: note: candidate constructor template not viable: requires 4 arguments, but 1 was provided
[build]   335 |         pair(tuple<_Args1...>&, tuple<_Args2...>&,
[build]       |         ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build]   336 |              _Index_tuple<_Indexes1...>, _Index_tuple<_Indexes2...>);
[build]       |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Comment (dschuff) [reply src/passes/Inlining.cpp:1347]: Ok, I think it's because `emplace` forwards all of the arguments to the constructor of the underlying pair (e.g. `std::pair<const wasm::Name, wasm::(anonymous namespace)::FunctionInfo>`, and  we are passing just the key, but a std::pair can't be constructed from just the first element. However `try_emplace` takes its first argument explicitly as the key, and forwards the rest of its arguments (none in this case) to construct the value. So it default-constructs the value, and creates the pair from the explicit key and the default-constructed value, and succeeds.

Comment (kripken) [reply src/passes/Inlining.cpp:1347]: I see, sounds good.

lgtm
