### PR TITLE
Fix source map entries offset when LEB is compressed.

### LINKED ISSUE #1591: Source map round-trip issues
See details in https://github.com/WebAssembly/binaryen/pull/1557#issuecomment-390446804 - we seem to move the annotations around, and it may be related to the warnings that show up.

### PR DESCRIPTION
**Pull request by yurydelendik**
Fixes #1591.

During fixup of the section and function sizes LEBs, the offsets needs to be adjusted by amount of moved bytes.

(Addresses regression after #1128)

### CODE REVIEW

File: src/wasm-binary.h [hunk 1]
```diff
@@ -734,7 +734,8 @@ class WasmBinaryWriter {
   MixedArena allocator;
 
   Function::DebugLocation lastDebugLocation;
-  size_t lastBytecodeOffset;
+  std::vector<std::pair<size_t, const Function::DebugLocation*>> sourceMapLocations;
+  size_t sectionStartAtSourceMapLocations;
```
Comment (kripken) [inline src/wasm-binary.h]: I think this is the size of `sourceMapLocations` at the section start? If so, how about calling it `sourceMapLocationsSizeAtSectionStart`? Or maybe `firstSourceMapLocationInSection`?

File: src/wasm/wasm-binary.cpp [hunk 2]
```diff
@@ -95,6 +95,7 @@ void WasmBinaryWriter::writeResizableLimits(Address initial, Address maximum,
 template<typename T>
 int32_t WasmBinaryWriter::startSection(T code) {
   o << U32LEB(code);
+  sectionStartAtSourceMapLocations = sourceMapLocations.size();
```
Comment (kripken) [inline src/wasm/wasm-binary.cpp]: could this and other places be behind `if (sourceMap)`?

File: src/wasm/wasm-binary.cpp [hunk 3]
```diff
@@ -106,6 +107,9 @@ void WasmBinaryWriter::finishSection(int32_t start) {
     assert(sizeFieldSize < MaxLEB32Bytes);
     std::move(&o[start] + MaxLEB32Bytes, &o[start] + MaxLEB32Bytes + size, &o[start] + sizeFieldSize);
     o.resize(o.size() - (MaxLEB32Bytes - sizeFieldSize));
+    for (size_t i = sectionStartAtSourceMapLocations; i < sourceMapLocations.size(); ++i) {
```
Comment (kripken) [inline src/wasm/wasm-binary.cpp]: `size_t => auto`

File: src/wasm/wasm-binary.cpp [hunk 4]
```diff
@@ -106,6 +107,9 @@ void WasmBinaryWriter::finishSection(int32_t start) {
     assert(sizeFieldSize < MaxLEB32Bytes);
     std::move(&o[start] + MaxLEB32Bytes, &o[start] + MaxLEB32Bytes + size, &o[start] + sizeFieldSize);
     o.resize(o.size() - (MaxLEB32Bytes - sizeFieldSize));
```
Comment (kripken) [inline src/wasm/wasm-binary.cpp]: `MaxLEB32Bytes - sizeFieldSize` is now used in multiple places (also elsewhere), how about saving it in a local called `adjustment` or `diff` or such?

File: src/wasm-binary.h [hunk 5]
```diff
@@ -734,7 +734,8 @@ class WasmBinaryWriter {
   MixedArena allocator;
 
   Function::DebugLocation lastDebugLocation;
-  size_t lastBytecodeOffset;
+  std::vector<std::pair<size_t, const Function::DebugLocation*>> sourceMapLocations;
```
Comment (kripken) [inline src/wasm-binary.h]: please add a comment explaining why we need this, maybe `we store source map locations until the section is placed at its final location (shrinking LEBs may cause changes there)`

File: src/wasm/wasm-binary.cpp [hunk 6]
```diff
@@ -1784,6 +1800,7 @@ void WasmBinaryBuilder::readFunctions() {
       }
     }
     currFunction = nullptr;
+    useDebugLocation = false;
```
Comment (kripken) [inline src/wasm/wasm-binary.cpp]: why is this change needed?

More generally, reading through the WasmBinaryBuilder's usage of `useDebugLocation`, I'm not sure I understand it. It seems to only be used locally in `WasmBinaryBuilder::readExpression`, but set in other locations, like the one added in this patch - are they even needed?

Comment (yurydelendik) [reply src/wasm/wasm-binary.cpp]: data segments have expressions -- this fixes a crash caused by using get_global from such expression that tried to access debug location information.

Comment (kripken) [reply src/wasm/wasm-binary.cpp]: Is the crash related to the other changes in this PR? Or is this fix unrelated?

Comment (yurydelendik) [reply src/wasm/wasm-binary.cpp]: I could reproduce crash with the debug information that now produced by the updated logic. I don't think we need an additional tests since I found this bug when was adjusting the test cases.

Comment (kripken) [reply src/wasm/wasm-binary.cpp]: Great, thanks!
