### PR TITLE
[parser] Fix bug when printing type builder errors

### LINKED ISSUE #6816: Wat parser assertion on invalid subtype
```wat
(module
 (rec
  (type $A (sub (struct (field i32))))
  (type $B (sub $B (struct (field i32) (field i32))))
 )
)
```
```
$ bin/wasm-opt a.wat
wasm-opt: src/parser/lexer.cpp:1141: wasm::WATParser::TextPos wasm::WATParser::Lexer::position(const char*) const: Assertion `size_t(c - buffer.data()) <= buffer.size()' failed.
Aborted
```
We should show an error on `$B` not being able to be a subtype of itself, but hit this assertion first.

cc @tlively

### PR DESCRIPTION
**Pull request by tlively**
The type index from the TypeBuilder error was mapped to a file location
incorrectly, resulting in an assertion failure.

Fixes #6816.

### CODE REVIEW

File: src/parser/parse-2-typedefs.cpp [hunk 1]
```diff
@@ -34,7 +34,7 @@ Result<> parseTypeDefs(
   if (auto* err = built.getError()) {
     std::stringstream msg;
     msg << "invalid type: " << err->reason;
-    return ctx.in.err(decls.typeDefs[err->index].pos, msg.str());
+    return ctx.in.err(decls.subtypeDefs[err->index].pos, msg.str());
```
Comment (kripken) [inline src/parser/parse-2-typedefs.cpp:37]: Why is this correct? I'm not sure how I would have known to think this was wrong. We are in `parseTypeDefs`, so shouldn't the `typeDefs` be relevant..? We even loop over `typeDefs on line 29.

Comment (tlively) [reply src/parser/parse-2-typedefs.cpp:37]: Each entry in `typeDefs` corresponds to a single recursion group (which may consist of a single top-level type definition without `(rec...)`, whereas each entry in `subtypeDefs` corresponds to a single type definition, which may or may not actually contain `(sub ...)`.

Better names would perhaps be `recTypeDefs` and `typeDefs` rather than `typeDefs` and `subtypeDefs`. Do you think it's worth updating those names here or in a separate PR?

Comment (kripken) [reply src/parser/parse-2-typedefs.cpp:37]: I see, thanks. Either way sgtm. lgtm as is if you prefer separately.
