### PR TITLE
[JS API] Throw useful exceptions on parse errors

### LINKED ISSUE #8256: parseText writes uncatchable usefull log to STDOUT or browser console.
Try the example bellow running on node.js or in a browser:
```js
binaryen.parseText(`(module
  (func (export "foo") (param $a i32) local.get $a)
  (func (export "bar") (paXam $b i32) local.get $b)
)`)
```
They will both log: `Fatal: 3:24: error: unrecognized instruction`

However a try/catch will only get the error `Program terminated with exit(1)`

An ugly hack replacing `console.error()` won't catch on the useful message either.

Can this method just throw the first (real) error, or add that on the `cause` of the catchable error?

### PR DESCRIPTION
**Pull request by kripken**
wasm-opt will just fatally error on invalid module inputs, but binaryen.js
is a library and users want to get something they can handle, and see
the actual error. This PR throws a C++ exception instead, and converts
it on the JS side.

Fixes #8256

### CODE REVIEW

File: src/js/binaryen.js-post.js [hunk 1]
```diff
@@ -3264,7 +3285,7 @@ Object.defineProperty(Module, 'readBinary', { writable: true });
 Module['readBinary'] = function(data) {
```
Comment (spotandjake) [inline src/js/binaryen.js-post.js:3285]: Just a nit but with #8122 I started trying to add some documentation with jsdoc how would we feel about continuing that pattern when possible? 
```suggestion
/**
   * Creates a module from binary data.
   * 
   * @param {Uint8Array} data - A Uint8Array containing a valid WebAssembly binary.
   * 
   * @return {Module} The constructed wasm module.
   *
   * @throws {Error} If the input is invalid or parsing fails.
   */
Module['readBinary'] = function(data) {
```

File: src/js/binaryen.js-post.js [hunk 2]
```diff
@@ -3273,7 +3294,7 @@ Module['readBinary'] = function(data) {
 Module['parseText'] = function(text) {
```
Comment (spotandjake) [inline src/js/binaryen.js-post.js:3294]: Same as above:

```suggestion
/**
   * Creates a module from Binaryen's s-expression text format (not official stack-style text format).
   * 
   * @param {string} text - A string containing a WebAssembly text module (Binaryen-style WAT).
   * 
   * @return {Module} The constructed wasm module.
   *
   * @throws {Error} If the input is invalid or parsing fails.
   */
Module['parseText'] = function(text) {
```

**Review by spotandjake — APPROVED** [review]
This looks great to me.

File: src/js/binaryen.js-post.js (hunk 1 above)
Comment (aheejin) [reply src/js/binaryen.js-post.js:3285]: Is this to autogenerate some doc? The comment here seems kind of obvious.

**Comment by aheejin** [comment]
Emscripten supports printing exception messages when run with `-sEXCEPTION_STACK_TRACES`. Can we use that without half-reimplementing this? Or do we not want the stack traces but only want the message?

**Comment by kripken** [comment]
> Or do we not want the stack traces but only want the message?

Yes, this is not focused on the stack trace in the exception. This is about being able to catch an exception in JS, and to get the message. Before this PR, a parse error just shut down the entire application, with no useful message for the code calling the binaryen.js library.

File: src/js/binaryen.js-post.js (hunk 1 above)
Comment (kripken) [reply src/js/binaryen.js-post.js:3285]: I assume @spotandjake you are thinking of autogenerating a docs page from the jsdocs comments?

That might be useful, though I'm not sure how much.

Comment (kripken) [reply src/js/binaryen.js-post.js:3285]: Let's leave the topic of adding jsdocs for separate discussion. I'll land this for now.
