### PR TITLE
Properly validate ref.cast when lacking a common supertype

### LINKED ISSUE #6738: Assertion failed in wasm-as when casting to externref
The following WAT code:
```.wat
(module
    (func (param eqref) (result externref)
        (ref.cast externref (local.get 0))))
```
crash the assembler with the following message:
```
Assertion failed: isRef() (/src/src/wasm/wasm-type.cpp: getHeapType: 930)
```
The problem is the cast to `externref`. The assembler should probably print an error message.

The crash was reproduced on the main branch (commit 22c28bd5a108f9bdacd1b60468e312903bcdf451).

### PR DESCRIPTION
**Pull request by kripken**
When lacking a common supertype the GLB operation makes the type of the cast
unreachable, which errors on `getHeapType` in the later code.

Fixes #6738

### CODE REVIEW

File: src/wasm/wasm-validator.cpp [hunk 1]
```diff
@@ -2749,6 +2749,17 @@ void FunctionValidator::visitRefCast(RefCast* curr) {
         curr->ref->type.isRef(), curr, "ref.cast ref must have ref type")) {
     return;
   }
+  // If the cast is unreachable but not the ref (we ruled out the former
+  // earlier), then the cast is unreachable because the cast type had no
+  // common supertype with the ref, which is invalid. This is the same as the
+  // check below us, but we must do it first (as getHeapType fails otherwise).
+  if (!shouldBeUnequal(
```
Comment (tlively) [inline src/wasm/wasm-validator.cpp:2756]: We could tighten this up even more by checking that the result type is a reference type. So if it somehow was set to i32 or something, we would still avoid the assertion failure.

Comment (kripken) [reply src/wasm/wasm-validator.cpp:2787]: Sounds good, I added that now as an extra test (it has a more generic error message, and I didn't want to lose the specific explanation for the supertype issue).

**Review by tlively — APPROVED** [review]
