### PR TITLE
Handle ArrayCmpxchg in Heap2Local

### LINKED ISSUE #8548: ArrayCmpxchg fuzz bug in Heap2Local
```wat
(module
 (rec
  (type $6 (array (mut eqref)))
  (type $0 (array (mut f64)))
  (type $14 (func (param (ref $6) eqref) (result eqref)))
 )
 (func $3 (type $14) (param $0 (ref $6)) (param $1 eqref) (result eqref)
  (array.atomic.rmw.cmpxchg $6
   (local.get $0)
   (i32.const 0)
   (array.new_default $0
    (i32.const 1)
   )
   (local.get $1)
  )
 )
)
```
```
$ bin/wasm-opt a.wat -all --heap2local
wasm-opt: src/wasm/wasm-type.cpp:923: const wasm::Struct& wasm::HeapType::getStruct() const: Assertion `isStruct()' failed.
Aborted                    (core dumped) bin/wasm-opt a.wat -all --heap2local
```
Looks like `Array2Struct::visitArrayCmpxchg` doesn't handle the case where the allocation we are removing is the expected value, not the ref. Likely it needs logic like `visitStructCmpxchg` @tlively ?

### PR DESCRIPTION
**Pull request by tlively**
We already took care of converting array cmpxchg operations to struct cmpxchg operations in Array2Struct, but we did so even when the optimized allocation flowed into the `expected` field. In that case, since we aren't optimizing the accessed object, we should keep the array cmpxchg and later optimize it in Heap2Local.

Fixes #8548.

### CODE REVIEW

File: src/passes/Heap2Local.cpp [hunk 1]
```diff
@@ -1445,9 +1481,20 @@ struct Array2Struct : PostWalker<Array2Struct> {
...
+      // The accessed array is being optimzied. Convert the ArrayCmpxchg into a
+      // StructCmpxchg.
+      replaceCurrent(builder.makeStructCmpxchg(
+        index, curr->ref, curr->expected, curr->replacement, curr->order));
+      return;
+    }
+
+    // The `expected` value must be getting optimized. Since the accessed object
+    // is remaining an array for now, do not change anything. The ArrayCmpxchg
+    // will be optimized later by Heap2Local.
```
Comment (kripken) [inline src/passes/Heap2Local.cpp]:
```suggestion
    // will be optimized later by Struct2Local.
```

File: src/passes/Heap2Local.cpp [hunk 2]
```diff
@@ -1215,6 +1215,40 @@ struct Struct2Local : PostWalker<Struct2Local> {
...
+                                       builder.makeDrop(curr->replacement),
+                                       arrayGet});
+      replaceCurrent(block);
+      // Since `ref` must be an array and arrays are processed before structs,
+      // it is not possible that `ref` will be processed later. We therefore do
+      // not need to do the extra bookkeeping that we needed to do for
+      // StructCmpxchg.
+      // analyzer.parents.setParent(curr->ref, setRefScratch);
+      // analyzer.scratchInfo.insert({setRefScratch, getRefScratch});
+      // analyzer.parents.setParent(getRefScratch, arrayGet);
```
Comment (tlively) [inline src/passes/Heap2Local.cpp]:
```suggestion
```
I had meant to delete these.
