### PR TITLE
[wasm-split] Do multi-split at once

### LINKED ISSUE #7725: [wasm-split] Not splitting correctly after wasm-opt
I'm trying to use wasm-split after having run wasm-opt on a module. The tool runs to completion and creates the modules as requested. However, when I try to load the modules I get an error:
`Uncaught RuntimeError: null function or function signature mismatch`

This comes from a call_indirect instruction:
`call_indirect (param (ref $type337)) (result (ref $type144)) $.H`

Pausing at that instruction and checking the $.H table, I see that table is empty. I believe this is a table generated by wasm-split.

If I do the same splits but without running wasm-opt on my module, everything loads as expected.

### PR DESCRIPTION
**Pull request by aheejin**
This does multi-splitting of modules at once, rather than splitting them one by one by doing 2-way split n times. Previously when we did multi-splitting we split the 1st module as the "secondary" module assuming all other functions belonging to 2nd-nth modules as "primary" module. And then we repeat the same task for the 2nd module, assuming 3rd-nth module functions belong to the "primary" module. This unnecessarily repeated some tasks that could have been done once.

This reduces the running time on a reproducer provided by @biggs0125 before (to fix #7725) from 232s to 80s on my machine, reducing it by around 66%.

Some side-products of this PR are:
- Now we only create a single table to host placeholders (or `ref.null`s in case of `--no-placeholders`) even when reference-types is enabled. Previously we created a table per secondary module, resulting in n tables.
- The names of trampoline functions have been changed in the tests, but semantically they are the same. (e.g. in `test/lit/wasm-split/multi-split.wast`) The reason for the change is, previously we split modules one by one, by the time we split the first module, it assumed functions belonging to other secondary modules were primary functions, but they later changed to trampolines as well. Now they are all named as trampolines, arguably enhancing readability.

---

Some detailed analysis run using the reproducer of #7725, a case where we split a module into 301 (1 primary + 300 secondary) modules:

- Before this PR:

Time: 232.9s

Task breakdown:
```
Task                                          Total Time (ms)      Percentage
---------------------------------------------------------------------------
shareImportableItems                               62139.5770          29.26%
classifyFunctions                                  42377.2849          19.95%
removeUnusedSecondaryElements                      33615.1043          15.83%
indirectReferencesToSecondaryFunctions             28047.9460          13.21%
indirectCallsToSecondaryFunctions                  25184.7922          11.86%
moveSecondaryFunctions                             14473.2277           6.82%
setupTablePatching                                  3126.4863           1.47%
initExportedPrimaryFuncs                            1674.4963           0.79%
exportImportCalledPrimaryFunctions                   936.1570           0.44%
thunkExportedSecondaryFunctions                      789.3036           0.37%
---------------------------------------------------------------------------
Overall Total                                     212364.3753         100.00%
```

- After this PR: (After addressing comments)

Time : 80.1s

Task breakdown:
```
Task                                          Total Time (ms)      Percentage
------------------------------------------------------------------------------
shareImportableItems                               35386.0000          48.46%
removeUnusedSecondaryElements                      27730.3000          37.98%
moveSecondaryFunctions                              4541.4800           6.22%
writeModule_secondary                               3176.7382           4.35%
writeModule_primary                                  997.8480           1.37%
exportImportCalledPrimaryFunctions                   649.7930           0.89%
indirectReferencesToSecondaryFunctions               269.4650           0.37%
indirectCallsToSecondaryFunctions                    136.9090           0.19%
classifyFunctions                                     88.8081           0.12%
setupTablePatching                                    40.6237           0.06%
thunkExportedSecondaryFunctions                        2.5536           0.00%
initExportedPrimaryFuncs                               0.5960           0.00%
------------------------------------------------------------------------------
Overall Total                                      73021.1146         100.00%
```

We can see time taken in `classifyFunctions`, `indirectReferencesToSecondaryFunctions`, and `indirectCallsToSecondaryFunctions` has reduced basically to nothing. This is because now we can scan all functions only once in those functions, where we used to scan the functions n times or similar.

Now `shareImportableItems` and `moveSecondaryFunctions` take up around 85% of the execution time. The reason `shareImportableItems` takes so long is the reproducer has 90k globals.
```
Analysis of shareImportableItems:
Sub-Task                                      Total Time (ms)      Percentage
-----------------------------------------------------------------------------
globals                                            41166.4904          98.35%
tables                                               535.5134           1.28%
tags                                                  10.3355           0.02%
memories                                               7.5937           0.02%
exports                                                1.5482           0.00%
-----------------------------------------------------------------------------
Total                                              41857.1000         100.00%
```
('exports' meaning processing existing exports)

We can probably improve this by selectively importing module items, as already noted by the existing TODO.

`moveSecondaryFunctions` basically just runs RemoveUnusedModuleElements on each module. But if we export only used items in `shareImportableItems`, running this pass may become unnecessary after all.

### CODE REVIEW

**Comment by aheejin** [comment]
"Hide whitespace" will make the diff easier to view.

File: src/ir/module-splitting.h [hunk 1]
```diff
@@ -47,11 +47,8 @@ namespace wasm::ModuleSplitting {
 static const Name LOAD_SECONDARY_MODULE("__load_secondary_module");
 
 struct Config {
-  // The set of functions to split into the secondary module. All others are
-  // kept in the primary module. Must not include the start function if it
-  // exists. May or may not include imported functions, which are always kept in
-  // the primary module regardless.
-  std::set<Name> secondaryFuncs;
+  // Module names to the functions that should be in the modules.
```
Comment (tlively) [inline src/ir/module-splitting.h]: Is this just secondary modules? It would good to clarify in the comment.

File: src/ir/module-splitting.h [hunk 2]
```diff
@@ -76,7 +73,7 @@ struct Config {
 };
 
 struct Results {
-  std::unique_ptr<Module> secondary;
+  std::map<Name, std::unique_ptr<Module>> secondaryPtrMap;
```
Comment (tlively) [inline src/ir/module-splitting.h]: Would it be reasonable to use a `std::vector` instead of a `std::map` here and in the `Config` to avoid having to worry about generating names before splitting? It seems that would dramatically reduce the number of necessary map lookups necessary because it would lend itself to using indices as the keys used to identify secondary modules and look up their associated data in vectors.

File: src/tools/wasm-split/wasm-split.cpp [hunk 3]
```diff
@@ -389,27 +389,29 @@ void multiSplitModule(const WasmSplitOptions& options) {
...
     if (line.empty()) {
       newSection = true;
       continue;
     }
     Name name = WasmBinaryReader::escape(line);
     if (newSection) {
-      currModule = name;
-      currFuncs = &moduleFuncs[name];
+      currModule = Names::getValidName(
+        name, [&](Name n) { return moduleNames.find(n) == moduleNames.end(); });
```
Comment (tlively) [inline src/tools/wasm-split/wasm-split.cpp]: Since the names are provided by the user, it might be better to fail loudly if a module name is repeated rather than silently changing one of the names to avoid the collision. (Or keep the current behavior of appending the new functions to the existing module, but that's also probably more dangerous than failing loudly.)

File: src/tools/wasm-split/wasm-split.cpp [hunk 4]
```diff
@@ -389,27 +389,29 @@ void multiSplitModule(const WasmSplitOptions& options) {
...
+      moduleNames.insert(currModule);
+      currFuncs = &config.moduleToFuncs[currModule];
```
Comment (tlively) [inline src/tools/wasm-split/wasm-split.cpp]: We can avoid the second lookup here by using the iterator returned by `moduleNames.insert`.

File: src/ir/module-splitting.cpp [hunk 5]
```diff
@@ -16,17 +16,19 @@
...
 //
 //   3. For any secondary function exported from the primary module, export in
 //      its place a trampoline function that makes an indirect call to its
 //      placeholder function (and eventually to the original secondary
 //      function), allocating a new table slot for the placeholder if necessary.
 //
-//   4. Replace all references to secondary functions in the primary module's
-//      table segments with references to imported placeholder functions.
+//   4. Replace all references to secondary functions in the primary module's or
+//      different secondary module's table segments with references to imported
```
Comment (tlively) [inline src/ir/module-splitting.cpp]:
```suggestion
//   4. Replace all references to each secondary module's functions in the primary module's and
//      each other secondary module's table segments with references to imported
```

File: src/ir/module-splitting.cpp [hunk 6]
```diff
@@ -35,24 +37,24 @@
 //
 //   6. For each primary function directly called from a secondary function,
 //      export the primary function if it is not already exported and import it
-//      into the secondary module.
+//      into the secondary module using it.
```
Comment (tlively) [inline src/ir/module-splitting.cpp]:
```suggestion
//      into each secondary module using it.
```

File: src/ir/module-splitting.cpp [hunk 7]
```diff
@@ -290,22 +292,23 @@ TableSlotManager::Slot TableSlotManager::getSlot(Name func, HeapType type) {
...
+  std::map<Name, std::unique_ptr<Module>> secondaryPtrMap;
 
   Module& primary;
-  Module& secondary;
 
-  const std::pair<std::set<Name>, std::set<Name>> classifiedFuncs;
-  const std::set<Name>& primaryFuncs;
-  const std::set<Name>& secondaryFuncs;
+  std::unordered_set<Name> primaryFuncs;
+  std::unordered_set<Name> allSecondryFuncs;
```
Comment (tlively) [inline src/ir/module-splitting.cpp]:
```suggestion
  std::unordered_set<Name> allSecondaryFuncs;
```

File: src/ir/module-splitting.cpp [hunk 8]
```diff
@@ -457,27 +459,44 @@ ModuleSplitter::classifyFunctions(Module& primary, const Config& config) {
...
+      allSecondryFuncs.insert(func->name);
+    }
+  }
+
+  // Move functions to each secondary module and create the reverse map
+  for (auto& [mod, funcs] : config.moduleToFuncs) {
+    moduleToFuncs[mod];
+    for (auto func : funcs) {
+      if (allSecondryFuncs.count(func)) {
+        moduleToFuncs[mod].insert(func);
```
Comment (tlively) [inline src/ir/module-splitting.cpp]:
```suggestion
    auto& funcs = moduleToFuncs[mod];
    for (auto func : funcs) {
      if (allSecondaryFuncs.count(func)) {
        funcs.insert(func);
```

File: src/ir/module-splitting.cpp [hunk 9]
```diff
@@ -457,27 +459,44 @@ ModuleSplitter::classifyFunctions(Module& primary, const Config& config) {
...
+      }
+    }
+  }
+  for (auto& [mod, funcs] : moduleToFuncs) {
+    for (auto func : funcs) {
+      funcToModule[func] = mod;
```
Comment (tlively) [inline src/ir/module-splitting.cpp]: Let's move this up to be right after the previous map insertion rather than splitting it into separate nested loops.

File: src/ir/module-splitting.cpp [hunk 10]
```diff
@@ -549,6 +576,7 @@ Name ModuleSplitter::getTrampoline(Name funcName) {
   auto func = builder.makeFunction(trampoline, oldFunc->type, {}, call);
   func->hasExplicitName = oldFunc->hasExplicitName;
   primary.addFunction(std::move(func));
+  primaryFuncs.insert(trampoline);
```
Comment (tlively) [inline src/ir/module-splitting.cpp:562]: Why is this addition necessary?

File: src/ir/module-splitting.cpp [hunk 11]
```diff
@@ -598,12 +626,22 @@ void ModuleSplitter::indirectReferencesToSecondaryFunctions() {
     InsertOrderedMap<Name, std::vector<RefFunc*>> map;
 
     void visitRefFunc(RefFunc* curr) {
-      if (parent.secondaryFuncs.count(curr->func)) {
+      Module* curModule = getModule();
```
Comment (tlively) [inline src/ir/module-splitting.cpp]:
```suggestion
      Module* currModule = getModule();
```

File: src/ir/module-splitting.cpp [hunk 12]
```diff
@@ -598,12 +626,22 @@ void ModuleSplitter::indirectReferencesToSecondaryFunctions() {
...
+      if (parent.allSecondryFuncs.count(curr->func) &&
+          (curModule == &parent.primary ||
+           curModule->name != parent.funcToModule.at(curr->func))) {
         map[curr->func].push_back(curr);
       }
     }
   } gatherer(*this);
   gatherer.walkModule(&primary);
+  for (auto& [mod, secondaryPtr] : secondaryPtrMap) {
+    gatherer.walkModule(secondaryPtr.get());
```
Comment (tlively) [inline src/ir/module-splitting.cpp:627]: It's certainly worth making this function-parallel in a separate PR.

File: src/ir/module-splitting.cpp [hunk 13]
```diff
@@ -649,16 +687,24 @@ void ModuleSplitter::indirectCallsToSecondaryFunctions() {
...
     void visitCall(Call* curr) {
-      if (!parent.secondaryFuncs.count(curr->target)) {
+      // Return if the call's target is not in one of the secondary module.
+      if (!parent.allSecondryFuncs.count(curr->target)) {
         return;
       }
-      auto* func = parent.secondary.getFunction(curr->target);
+      // Return if the current module is the same module as the call's target,
+      // because we don't need a call_indirect within the same module.
+      Module* curModule = getModule();
```
Comment (tlively) [inline src/ir/module-splitting.cpp]:
```suggestion
      Module* currModule = getModule();
```

File: src/ir/module-splitting.cpp [hunk 14]
```diff
@@ -670,42 +716,54 @@ void ModuleSplitter::indirectCallsToSecondaryFunctions() {
                                  curr->isReturn)));
     }
   };
-  CallIndirector(*this).walkModule(&primary);
+  CallIndirector callIndirector(*this);
+  callIndirector.walkModule(&primary);
+  for (auto& [mod, secondaryPtr] : secondaryPtrMap) {
+    callIndirector.walkModule(secondaryPtr.get());
```
Comment (tlively) [inline src/ir/module-splitting.cpp:706]: This can be parallelized in a separate PR, too.

File: src/ir/module-splitting.cpp [hunk 15]
```diff
@@ -670,42 +716,54 @@ void ModuleSplitter::indirectCallsToSecondaryFunctions() {
...
-        const std::set<Name>& primaryFuncs;
-        std::vector<Name>& calledPrimaryFuncs;
-        CallCollector(const std::set<Name>& primaryFuncs,
-                      std::vector<Name>& calledPrimaryFuncs)
-          : primaryFuncs(primaryFuncs), calledPrimaryFuncs(calledPrimaryFuncs) {
-        }
-        void visitCall(Call* curr) {
-          if (primaryFuncs.count(curr->target)) {
-            calledPrimaryFuncs.push_back(curr->target);
+  //   using RefFuncMap = InsertOrderedMap<Name, std::vector<RefFunc*>>;
```
Comment (tlively) [inline src/ir/module-splitting.cpp]: Stale?

File: src/ir/module-splitting.cpp [hunk 16]
```diff
@@ -670,42 +716,54 @@ void ModuleSplitter::indirectCallsToSecondaryFunctions() {
...
-  CallIndirector(*this).walkModule(&primary);
+  CallIndirector callIndirector(*this);
+  callIndirector.walkModule(&primary);
+  for (auto& [mod, secondaryPtr] : secondaryPtrMap) {
+    callIndirector.walkModule(secondaryPtr.get());
+  }
 }
 
 void ModuleSplitter::exportImportCalledPrimaryFunctions() {
   // Find primary functions called/referred in the secondary module.
```
Comment (tlively) [inline src/ir/module-splitting.cpp]:
```suggestion
  // Find primary functions called/referred to from the secondary modules.
```

File: src/ir/module-splitting.cpp [hunk 17]
```diff
@@ -670,42 +716,54 @@ void ModuleSplitter::indirectCallsToSecondaryFunctions() {
...
-    });
-  std::set<Name> calledPrimaryFuncs;
-  for (auto& entry : callCollector.map) {
-    auto& calledFuncs = entry.second;
-    calledPrimaryFuncs.insert(calledFuncs.begin(), calledFuncs.end());
-  }
+        };
+        CallCollector collector(primaryFuncs, calledPrimaryFuncs);
+        collector.setModule(secondary);
+        collector.walkFunction(func);
```
Comment (tlively) [inline src/ir/module-splitting.cpp]:
```suggestion
        CallCollector(primaryFuncs, calledPrimaryFuncs).walkFunctionInModule(func, secondary);
```

File: src/ir/module-splitting.cpp [hunk 18]
```diff
@@ -670,42 +716,54 @@ void ModuleSplitter::indirectCallsToSecondaryFunctions() {
...
+      });
+
+    CalledPrimaryToModules calledPrimaryToModules;
```
Comment (tlively) [inline src/ir/module-splitting.cpp:740]: I wonder if we need to do a `walkModuleCode` or similar here to pick up function references in globals, too. That can be investigated separately, though.

File: src/ir/module-splitting.cpp [hunk 19]
```diff
@@ -860,64 +926,76 @@ void ModuleSplitter::shareImportableItems() {
       Name exportName = Names::getValidExportName(primary, baseName);
       primary.addExport(new Export(exportName, kind, primaryItem.name));
       secondaryItem.base = exportName;
+      exports[std::make_pair(kind, primaryItem.name)] = exportName;
```
Comment (tlively) [inline src/ir/module-splitting.cpp:911]: Is this a fix to avoid unnecessary duplicate exports? If so, it might be nice to separate that out to reduce test churn in this PR.

File: test/lit/wasm-split/multi-split-escape-names.wast [hunk 20]
```diff
@@ -20,13 +22,13 @@
 
  ;; MOD1:      (type $2 (func (result i32)))
 
- ;; MOD1:      (import "" "table" (table $timport$0 1 funcref))
+ ;; MOD1:      (import "" "table" (table $timport$0 3 funcref))
 
- ;; MOD1:      (import "" "std::operator<<\\28std::__2::basic_ostream<char\\2c\\20std::__2::char_traits<char>>&\\2c\\20wasm::Module&\\29" (func $std::operator<<\28std::__2::basic_ostream<char\2c\20std::__2::char_traits<char>>&\2c\20wasm::Module&\29 (result f32)))
+ ;; MOD1:      (import "" "trampoline_std::operator<<\\28std::__2::basic_ostream<char\\2c\\20std::__2::char_traits<char>>&\\2c\\20wasm::Module&\\29" (func $trampoline_std::operator<<\28std::__2::basic_ostream<char\2c\20std::__2::char_traits<char>>&\2c\20wasm::Module&\29 (result f32)))
```
Comment (tlively) [inline test/lit/wasm-split/multi-split-escape-names.wast:27]: Can we split the unrelated improvements like adding "trampoline" prefixes to names out into preliminary PRs to minimize test churn? It would also be nice if we can avoid changing the order of trampoline functions in the output (but I can imagine that might be more effort than it's worth).

**Review by tlively — COMMENTED** [review]
Great work! This is a really nice improvement.

File: src/ir/module-splitting.cpp [hunk 21]
```diff
@@ -649,16 +686,24 @@ void ModuleSplitter::indirectCallsToSecondaryFunctions() {
   // corresponding table indices instead.
   struct CallIndirector : public PostWalker<CallIndirector> {
     ModuleSplitter& parent;
-    Builder builder;
-    CallIndirector(ModuleSplitter& parent)
-      : parent(parent), builder(parent.primary) {}
-    // Avoid visitRefFunc on element segment data
-    void walkElementSegment(ElementSegment* segment) {}
```
Comment (aheejin) [inline src/ir/module-splitting.cpp:656]: This is unnecessary because `CallIndirector` does not have `visitRefFunc`. (I guess this class used to have `visitRefFunc` and this was added then)

File: src/ir/module-splitting.cpp (hunk 15 above)
Comment (aheejin) [reply src/ir/module-splitting.cpp]: Removed in https://github.com/WebAssembly/binaryen/commit/7de862e84d0b0f846c194da56c4aa0b553f2f334.

File: src/ir/module-splitting.cpp (hunk 17 above)
Comment (aheejin) [reply src/ir/module-splitting.cpp]: Manually applied in https://github.com/WebAssembly/binaryen/pull/7956/commits/aece184d443ca62e2b72bea3fcfaf2590b02c417. (Automatic application was not possible because I changed variable names)

File: src/ir/module-splitting.h (hunk 1 above)
Comment (aheejin) [reply src/ir/module-splitting.h]: We don't have this variable anymore after https://github.com/WebAssembly/binaryen/pull/7956/commits/0c853c5ee3b2cce3211157ff2dff7b5b309241da.

File: src/ir/module-splitting.h (hunk 2 above)
Comment (aheejin) [reply src/ir/module-splitting.h]: Done in https://github.com/WebAssembly/binaryen/pull/7956/commits/0c853c5ee3b2cce3211157ff2dff7b5b309241da. Now we don't pass names from `wasm-split.cpp` to `ModuleSplitter` at all. We needed a reverse map of function name to index though.

File: src/tools/wasm-split/wasm-split.cpp (hunk 4 above)
Comment (aheejin) [reply src/tools/wasm-split/wasm-split.cpp]: We don't have this map anymore after https://github.com/WebAssembly/binaryen/pull/7956/commits/0c853c5ee3b2cce3211157ff2dff7b5b309241da.

File: src/tools/wasm-split/wasm-split.cpp (hunk 3 above)
Comment (aheejin) [reply src/tools/wasm-split/wasm-split.cpp]: Done: https://github.com/WebAssembly/binaryen/pull/7956/commits/7e7fa664cea6124a3f295575fac84d7176f96c01

File: src/ir/module-splitting.cpp (hunk 9 above)
Comment (aheejin) [reply src/ir/module-splitting.cpp]: After https://github.com/WebAssembly/binaryen/commit/0c853c5ee3b2cce3211157ff2dff7b5b309241da, we populate `funcToSecondaryIndex` (not `funcToModule` because we use indices now) in `moveSecondaryFunction`.

File: src/ir/module-splitting.cpp (hunk 19 above)
Comment (aheejin) [reply src/ir/module-splitting.cpp:911]: It doesn't make any more test churn. This does not have any effect on the current main branch because, we only do a single two-way split at a time, there's no duplicate export. For example, everything you export when you split the first module becomes "existing exports" you need to process in the beginning of this function by the time you split second module here: https://github.com/WebAssembly/binaryen/blob/2010baabe480c3f68f89377f171f0642b7801287/src/ir/module-splitting.cpp#L833-L843

File: src/ir/module-splitting.cpp (hunk 10 above)
Comment (aheejin) [reply src/ir/module-splitting.cpp:562]: So that they can be correctly exported in `exportImportCalledPrimaryFunctions`.

For example, in the case of `test/lit/wasm-split/multi-split.wast`, after `indirectReferencesToSecondaryFunctions`, the secondary modules are like this:

Module 1:
```wast
(func $A
  ... (ref.func $A) ...
  ... (ref.func $trampoline_B) ...
  ... (ref.func $trampoline_C) ...
)
```
Module 2:
```wast
(func $B
  ... (ref.func $trampoline_A) ...
  ... (ref.func $B) ...
  ... (ref.func $trampoline_C) ...
)
```
Module 3:
```wast
(func $C
  ... (ref.func $trampoline_A) ...
  ... (ref.func $trampoline_B) ...
  ... (ref.func $C) ...
)
```

From the point of Module 1, `trampoline_B` and `trampoline_C` are primary functions that need to be exported from the primary module. But without this addition, newly created trampolines in `indirectReferencesToSecondaryFunctions` weren't in `primaryFuncs` and thus were not exported in `exportImportCalledPrimaryFunctions`.

The reason we didn't need this until now was, because we only did a two-way split at a time, the trampolines we created when splitting Module 1 were treated as normal primary functions by the time we split Module 2.

File: src/ir/module-splitting.cpp (hunk 12 above)
Comment (aheejin) [reply src/ir/module-splitting.cpp:627]: Do you mean function-parallel (using `ParallelFunctionAnalysis`) or module-level parallel (= parallelizing this `for` loop)? You said function but you highlighted the `for` loop so I'm checking to be sure.

Before this patch, I tried using `ParallelFunctionAnalysis` here and also in `indirectCallsToSecondaryFunctions` but it didn't improve runtime (maybe cache reasons? not sure). Also now this function only takes up 0.4% of the runtime so I'm not sure how much speedup we can gain. It's actually surprising that this and `indirectCallsToSecondaryFunctions` take so little time.

File: src/ir/module-splitting.cpp (hunk 14 above)
Comment (aheejin) [reply src/ir/module-splitting.cpp:706]: https://github.com/WebAssembly/binaryen/pull/7956#discussion_r2418184301 applies here too. (with 0.17% of runtime)

File: src/ir/module-splitting.cpp (hunk 18 above)
Comment (aheejin) [reply src/ir/module-splitting.cpp:740]: Secondary modules don't have (defined) globals, because we don't split them, no?

File: test/lit/wasm-split/multi-split-escape-names.wast (hunk 20 above)
Comment (aheejin) [reply test/lit/wasm-split/multi-split-escape-names.wast:27]: About the 'trampoline' name:

Not sure how I can only update names without this patch. We were already adding `trampoline_` to trampolines. The reason many trampolines didn't have that was because we only did a two-way split at once. 

For example, _after_ this PR, in the case of`test/lit/wasm-split/multi-split.wast`, after 
`indirectReferencesToSecondaryFunctions`, secondary modules are like

Module 1:
```wast
(func $A
  ... (ref.func $A) ...
  ... (ref.func $trampoline_B) ...
  ... (ref.func $trampoline_C) ...
)
```
Module 2:
```wast
(func $B
  ... (ref.func $trampoline_A) ...
  ... (ref.func $B) ...
  ... (ref.func $trampoline_C) ...
)
```
Module 3:
```wast
(func $C
  ... (ref.func $trampoline_A) ...
  ... (ref.func $trampoline_B) ...
  ... (ref.func $C) ...
)
```

But before this patch, we do this one by one. When we split Module 1, `B` and `C` are still considered primary functions. So It will be like:
Module 1:
```wast
(func $A
  ... (ref.func $A) ...
  ... (ref.func $B) ...
  ... (ref.func $C) ...
)
```
And the primary module becomes
```wast
(func $B
  ... (ref.func $trampoline_A) ...
  ... (ref.func $B) ...
  ... (ref.func $C) ...
)
(func $C
  ... (ref.func $trampoline_A) ...
  ... (ref.func $B) ...
  ... (ref.func $C) ...
)
```

When we split Module 2, now `B` is a secondary function. This time `C` is still a primary function, so
Module 2:
```wast
(func $B
  ... (ref.func $trampoline_A) ...
  ... (ref.func $B) ...
  ... (ref.func $C) ...
)
```
And the primary module becomes
```wast
(func $C
  ... (ref.func $trampoline_A) ...
  ... (ref.func $trampoline_B) ...
  ... (ref.func $C) ...
)
```
And the already exported `B` in the primary module will become
```wast
(export "B" (func $trampoline_B))
```

So this is the reason that some trampolines don't have `trampoline_` even if they all end up being trampolines. `B` and `C` are not secondary functions by the time we split `A`. When we split `A`, without scanning all configuration for the other modules, it is not possible to know that `B` and `C` will be split later.

---

About the order:

Let's use `multi-split.wast` as an example here too. Before this PR, the reason the trampoline order was `trampoline_A`->`trampoline_B`->`trampoline_C` was, because we split `A` first, and `indirectReferencesToSecondaryFunctions`  created `trampoline_A` first.

With this PR, `indirectReferencesToSecondaryFunctions` still scans function `A` first. But when scanning function `A`, `Gatherer` gathers `ref.func`s that are in other modules (= primary, Module2, and Module3). And the first intermodule ref.func it encounters is `ref.func $B`, and then `ref.func $C`. And `Gatherer` uses `InsertOrderedMap`, trampolines are created in the order of encounters. (Even if we change this to `std::map` or something, the test churns are unavoidable)

So yeah in this case too, it's unclear how can we maintain the test's trampoline order. Probably we can start from the second module and go to module N and then come back and finish with module 1, but this would be very weird.

File: src/ir/module-splitting.cpp (hunk 12 above)
Comment (tlively) [reply src/ir/module-splitting.cpp:627]: I had been thinking of `ParallelFunctionAnalysis`. I agree it's surprising that this takes so little time.

**Comment by aheejin** [comment]
After addressing comments, the execution time went down from 88s to 80s, and the improvement compared to `main` is around 66%. Probably thanks to less map lookups 😀

File: src/tools/wasm-split/wasm-split.cpp [hunk 22]
```diff
@@ -389,27 +389,37 @@ void multiSplitModule(const WasmSplitOptions& options) {
...
 
+  ModuleSplitting::Config config;
   std::string line;
   bool newSection = true;
+  std::vector<Name> moduleNames;
+  std::unordered_set<Name> moduleNameSet;
   while (std::getline(manifest, line)) {
     if (line.empty()) {
       newSection = true;
+      if (currFuncs->empty()) {
```
Comment (tlively) [inline src/tools/wasm-split/wasm-split.cpp]:
```suggestion
      if (currFuncs->empty() && !options.quiet) {
```

File: src/ir/module-splitting.cpp (hunk 18 above)
Comment (tlively) [reply src/ir/module-splitting.cpp:740]: Ah right, of course.

File: src/ir/module-splitting.cpp (hunk 10 above)
Comment (tlively) [reply src/ir/module-splitting.cpp:562]: Makes sense, thanks!

File: src/ir/module-splitting.cpp (hunk 19 above)
Comment (tlively) [reply src/ir/module-splitting.cpp:911]: Got it.

File: test/lit/wasm-split/multi-split-escape-names.wast (hunk 20 above)
Comment (tlively) [reply test/lit/wasm-split/multi-split-escape-names.wast:27]: Tricky stuff. Thanks for the thorough explanations.
