### PR TITLE
Don't create memory sections for imported memories; fixes #772

### LINKED ISSUE #772: When importing a memory/table, do not define a memory/table section
As stated in https://github.com/WebAssembly/design/blob/master/Modules.md#linear-memory-section:

    In the MVP, every memory is a default memory and thus there may be at most
    one linear memory import or linear memory section.

So to my understanding, it is incorrect to write a memory section when a memory is imported, and ditto for tables.

edit: the table section has the same kind of wording:

    In the MVP, every table is a default table and thus there may be at most one table import or table section.

### PR DESCRIPTION
**Pull request by bnjbvr**
I've made a naive and simple code similar to what's being done for tables. Tests all pass until I get an error just before running the torture tests:

```
[ checking torture testcases... ]

Traceback (most recent call last):
  File "./check.py", line 558, in <module>
    import test.waterfall.src.link_assembly_files as link_assembly_files
ImportError: No module named waterfall.src.link_assembly_files
```

### CODE REVIEW

File: src/wasm-s-parser.h [hunk 1]
```diff
@@ -1470,6 +1469,12 @@ class SExpressionWasmBuilder {
       } else if (inner[0]->str() == IMPORT) {
         importModule = inner[1]->str();
         importBase = inner[2]->str();
+        auto im = make_unique<Import>();
+        im->kind = ExternalKind::Memory;
+        im->module = importModule;
+        im->base = importBase;
+        im->name = importModule; // + importBase;
```
Comment (dschuff) [inline src/wasm-s-parser.h]: This was an extraneous comment that I accidentally left in in the previous PR; you don't need to copy it :) I don't think the name actually matters; maybe @kripken knows better and maybe even we should come up with a better name for this PR I think it's fine to leave as-is, just without the comment. (Bonus points if you remove the corresponding comment from the table part :) )

Comment (bnjbvr) [inline src/wasm-s-parser.h]: OK, I took it as a reminder for later to actually construct a string concatening importModule.importBase. Will remove both.

**Comment by dschuff** [comment]
The error running the tests looks unrelated to the change. That missing script comes from the waterfall piece that is supposed to get downloaded by check.py. Maybe that didn't work for you? What happens if you run check.py with `--only-prepare` first? (IIRC that's supposed to do the setup without running the tests).

**Comment by bnjbvr** [comment]
I've tried `check.py --only-prepare` and then re-running with no more success. Continuous integration is happy, though :)

**Comment by dschuff** [comment]
What happens if you remove the `test/local_revision` file and then try?

**Comment by bnjbvr** [comment]
Not better:

```
$ ./check.py
(downloading waterfall 11453: https://storage.googleapis.com/wasm-llvm/builds/linux/11453/wasm-binaries-11453.tbz2)
(unpacking)
(noting local revision)
trying waterfall clang at /code/binaryen/test/wasm-install/wasm-install/bin/clang
[... tests execute ...]
[ checking torture testcases... ]

Traceback (most recent call last):
  File "./check.py", line 558, in <module>
    import test.waterfall.src.link_assembly_files as link_assembly_files
ImportError: No module named waterfall.src.link_assembly_files
```

The `test/waterfall` directory is actually empty.

**Comment by dschuff** [comment]
Oh, I forgot; `test/waterfall` is actually a git submodule and not part of
the waterfall build. So you probably just need to run `git submodule update
--init` to get the submodules checked out.

**Comment by bnjbvr** [comment]
Right, this is the command I was missing. I can now run all the tests locally and see that they all pass. Cheers!

**Comment by kripken** [comment]
lgtm too, thanks!
