### PR TITLE
Fix inner block problem with 'catch'

### LINKED ISSUE #3114: exnref-related error in writing binary
[emcc-0-base.wasm.gz](https://github.com/WebAssembly/binaryen/files/5204879/emcc-0-base.wasm.gz)

The attached wasm file is the wasm-ld output for `test_exceptions_3` with wasm exceptions. The wasm-ld output is valid after https://bugs.llvm.org/show_bug.cgi?id=47413 but the test cannot be enabled yet as running
```
wasm-opt emcc-0-base.wasm -o out.wasm
```
results in an invalid wasm, wabt says
```
$ wasm2wat   --enable-all out.wasm
b.wasm:0000f7e: error: type mismatch in local.set, expected [exnref] but got []
0000000: error: type mismatch in try catch, expected [] but got [exnref]
b.wasm:00039f7: error: type mismatch in function, expected [] but got [i32, i32, i32, i32]
b.wasm:0004501: error: type mismatch in function, expected [] but got [i32]
b.wasm:00048b8: error: type mismatch in function, expected [] but got [i32]
[..]
```
(doing another roundtrip results in a valid wasm, and is why this wasn't noticed before - we do one fewer roundtrip now on many tests since at `-O0` we don't run wasm-opt at all if we don't need to).

cc @aheejin

### PR DESCRIPTION
**Pull request by aheejin**
Fixes #3114.

### CODE REVIEW

File: src/wasm/wasm-binary.cpp [hunk 1]
```diff
@@ -2692,21 +2692,11 @@ void WasmBinaryBuilder::visitBlock(Block* curr) {
 }
 
 // Gets a block of expressions. If it's just one, return that singleton.
-// numPops is the number of pop instructions we add before starting to parse the
-// block. Can be used when we need to assume certain number of values are on top
-// of the stack in the beginning.
-Expression* WasmBinaryBuilder::getBlockOrSingleton(Type type,
-                                                   unsigned numPops) {
```
Comment (aheejin) [inline src/wasm/wasm-binary.cpp:2699]: This `numPops` thing was added to be used by `catch`, but now it does not use this method anymore, so deleted it.

File: src/wasm/wasm-binary.cpp [hunk 2]
```diff
@@ -2757,12 +2747,12 @@ void WasmBinaryBuilder::visitLoop(Loop* curr) {
   auto start = expressionStack.size();
   processExpressions();
   size_t end = expressionStack.size();
+  if (start > end) {
+    throwError("block cannot pop from outside");
+  }
```
Comment (aheejin) [inline src/wasm/wasm-binary.cpp:2752]: This was just moved to make code cleaner (in my opinion)

File: test/break-within-catch.wasm.fromBinary [hunk 3]
```diff
@@ -0,0 +1,19 @@
+(module
```
Comment (aheejin) [inline test/break-within-catch.wasm.fromBinary:1]: The original `break-within-catch.wasm`'s `wasm2wat` output is this:
```wat
(module
  (type (;0;) (func))
  (func (;0;) (type 0)
    try  ;; label = @1
      nop
    catch
      drop
      br 0 (;@1;)
    end))
```

File: src/wasm/wasm-binary.cpp [hunk 4]
```diff
@@ -4845,11 +4836,86 @@ void WasmBinaryBuilder::visitTry(Try* curr) {
...
-    throwError("try should end with end");
+
+  if (breakTargetNames.find(catchLabel) == breakTargetNames.end()) {
+    out = curr;
+  } else {
+    // Create a new block that encloses whole try-catch
+    auto* block = allocator.alloc<Block>();
+    block->list.push_back(curr);
+    block->name = catchLabel;
+    block->finalize(curr->type);
```
Comment (kripken) [inline src/wasm/wasm-binary.cpp:4914]: this could use a Builder and `builder.makeBlock(catchLabel, curr)` on a single line.

(maybe the previous block allocation too, but it's not an obvious win there since you need to manually call `pushBlockElements` anyhow.)

File: src/wasm/wasm-binary.cpp [hunk 5]
```diff
@@ -4845,11 +4836,86 @@ void WasmBinaryBuilder::visitTry(Try* curr) {
...
+    curr->catchBody = block;
+  }
   curr->finalize(curr->type);
-  if (lastSeparator != BinaryConsts::End) {
-    throwError("try should end with end");
+
+  if (breakTargetNames.find(catchLabel) == breakTargetNames.end()) {
+    out = curr;
+  } else {
+    // Create a new block that encloses whole try-catch
```
Comment (kripken) [inline src/wasm/wasm-binary.cpp:4910]:
```suggestion
    // Create a new block that encloses the whole try-catch
```

File: src/wasm/wasm-binary.cpp [hunk 6]
```diff
@@ -4845,11 +4836,86 @@ void WasmBinaryBuilder::visitTry(Try* curr) {
   if (lastSeparator != BinaryConsts::Catch) {
     throwError("No catch instruction within a try scope");
   }
-  curr->catchBody = getBlockOrSingleton(curr->type, 1);
+
+  // For simplicity, we create an inner block within the catch body too, but one
```
Comment (kripken) [inline src/wasm/wasm-binary.cpp:4840]:
```suggestion
  // For simplicity, we create an inner block within the catch body too, but the one
```

File: src/wasm/wasm-binary.cpp [hunk 7]
```diff
@@ -4845,11 +4836,86 @@ void WasmBinaryBuilder::visitTry(Try* curr) {
...
+  // within 'catch' should be omitted when we write out the binary back later,
```
Comment (kripken) [inline src/wasm/wasm-binary.cpp:4841]:
```suggestion
  // within the 'catch' *must* be omitted when we write out the binary back later,
```

File: src/wasm/wasm-binary.cpp [hunk 8]
```diff
@@ -4845,11 +4836,86 @@ void WasmBinaryBuilder::visitTry(Try* curr) {
...
+  // because 'catch' instruction pushes a value onto the stack and the inner
```
Comment (kripken) [inline src/wasm/wasm-binary.cpp:4842]:
```suggestion
  // because the 'catch' instruction pushes a value onto the stack and the inner
```

**Review by kripken — APPROVED** [review]
Nice!

Comment changes are just suggestions, not sure how much they help.

File: src/wasm/wasm-binary.cpp (hunk 4 above)
Comment (aheejin) [reply src/wasm/wasm-binary.cpp]: Done. Left the previous allocation as is, because of `pushBlockElements` as you said.
