### PR TITLE
OptimizeInstructions: Optimize `unsigned(x) >= 0 => i32(1)` even with side effects

### LINKED ISSUE #7425: `-O3` Regression: `OptimizeInstructions` for `unsigned(x) >= 0   =>   i32(1)` Skips Side-Effecting expr
Given the following code:

``` webassembly
(module
  (import "External" "external_function" (func $external_function))
  (func $_start (result i32)
    (local $0 i32) (local $1 i32) (local $2 i32) (local $3 i32)
    call $foo
    local.set $1
    i32.const 1
    local.set $2
    local.get $1
    local.get $2
    i32.and
    i32.const 0
    i32.ge_s
    local.set $3
    i32.const 0
    local.set $0
    block ;; label = @1
      local.get $3
      br_if 0 (;@1;)
      call $external_function
      i32.const 0
      local.set $0
    end
    local.get $0)
  (func $foo (result i32)
    i32.const 0
    i32.load
    return)
  (memory 1)
  (export "_start" (func $_start)))
```

`wasm-opt -O2 -all -S` generates

<details>
<summary> Code (call $external_function is eliminated) </summary>

``` webassembly
(module
 (type $0 (func (result i32)))
 (memory $0 1)
 (export "_start" (func $_start))
 (func $_start (type $0) (result i32)
  (drop
   (i32.load
    (i32.const 0)
   )
  )
  (i32.const 0)
 )
)
```

</details>

`wasm-opt -O3 -all -S` generates

<details>
<summary> Code (call $external_function is not eliminated) </summary>

```webassembly
(module
 (type $0 (func))
 (type $1 (func (result i32)))
 (import "External" "external_function" (func $external_function (type $0)))
 (memory $0 1)
 (export "_start" (func $_start))
 (func $_start (type $1) (result i32)
  (if
   (i32.lt_u
    (i32.and
     (i32.load
      (i32.const 0)(module
 (type $0 (func))
 (type $1 (func (result i32)))
 (import "External" "external_function" (func $external_function (type $0)))
 (memory $0 1)
 (export "_start" (func $_start))
 (func $_start (type $1) (result i32)
  (if
   (i32.lt_u
    (i32.and
     (i32.load
      (i32.const 0)
     )
     (i32.const 1)
    )
    (i32.const 0)
   )
   (then
    (call $external_function)
   )
  )
  (i32.const 0)
 )
)
     )
     (i32.const 1)
    )
    (i32.const 0)
   )
   (then
    (call $external_function)
   )
  )
  (i32.const 0)
 )
)
```

</details>

**Problem Description**

The case which can trigger O3 regression is similar to the case in #7418  (but different).

In short, currently peephole optimization rule for `unsigned (expression) > 1` is limited for it doesn't apply if the `expression` has side effects.It can't do this peephole optimization:

Image

### PR DESCRIPTION
**Pull request by xuruiyang2002**
Current peephole optimization for unsigned(x) >= 0 => i32(1) is restrictive—actually we could replace the condition with const (1 here), while preserving any necessary side effects from the original expression or its children(by getDroppedChildrenAndAppend).

Image

Fixes #7425

### CODE REVIEW

File: src/passes/OptimizeInstructions.cpp [hunk 1]
```diff
@@ -557,11 +557,11 @@ struct OptimizeInstructions
         //       if pure.
```
Comment (kripken) [inline src/passes/OptimizeInstructions.cpp:557]: This TODO can be removed.

File: test/lit/passes/optimize-instructions-mvp.wast [hunk 2]
```diff
@@ -11575,10 +11595,22 @@
       (local.get $x)
       (i32.const 0)
     ))
+    (drop (i32.ge_u
+      (i32.load
+       (i32.const 0)
+      )
```
Comment (kripken) [inline test/lit/passes/optimize-instructions-mvp.wast:11601]: Same comment as the other PR, please use `(local.get $x)` (1 line) rather than a load with a constant (3 lines).

File: src/passes/OptimizeInstructions.cpp (hunk 1 above)
Comment (xuruiyang2002) [reply src/passes/OptimizeInstructions.cpp]: Done. I've removed the TODO. Thanks for the review.

File: test/lit/passes/optimize-instructions-mvp.wast (hunk 2 above)
Comment (kripken) [reply test/lit/passes/optimize-instructions-mvp.wast:11601]: (this was my confusion in the other PR)

File: test/lit/passes/optimize-instructions-mvp.wast [hunk 3]
```diff
@@ -17304,20 +17336,20 @@
...
   ;; CHECK-NEXT:     (i32.const 1)
   ;; CHECK-NEXT:    )
-  ;; CHECK-NEXT:    (i32.const 1)
   ;; CHECK-NEXT:   )
-  ;; CHECK-NEXT:   (i32.const 0)
+  ;; CHECK-NEXT:   (i32.const 1)
   ;; CHECK-NEXT:  )
-  ;; CHECK-NEXT: )
   (func $skip-added-constants-zero-b (result i32)
     ;; Parallel case to the above, with a zero in the added constant. We do not
```
Comment (kripken) [inline test/lit/passes/optimize-instructions-mvp.wast:17354]: This comment should be updated. Please add something like `(But we do optimize the outer i32.ge_u away.)` That way the reader will not be surprised to see a comment saying "we do not optimize" but some amount of optimization does happen.

Comment (xuruiyang2002) [reply test/lit/passes/optimize-instructions-mvp.wast]: Thanks for catching that. Now it have been updated.

**Review by kripken — APPROVED** [review]
