### PR TITLE
Fix parsing error on array.new_fixed on non-array

### LINKED ISSUE #7602: wasm-opt crashes with "Assertion `isArray()' failed" instead of type error
Binaryen version: 123
How to reproduce:

```wasm
(module

  (type $string (struct (field anyref)))

  (global $s (ref $string)
    (array.new_fixed $string 1 (i32.const 64)))
)
```

```
$ wasm-opt -all repro.wat
wasm-opt: /build/source/src/wasm/wasm-type.cpp:930: wasm::Array wasm::HeapType::getArray() const: Assertion `isArray()' failed.
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by kripken**
Fixes #7602

### CODE REVIEW

File: src/wasm/wasm-ir-builder.cpp [hunk 1]
```diff
@@ -2213,6 +2213,9 @@ Result<> IRBuilder::makeArrayNewElem(HeapType type, Name elem) {
 
 Result<> IRBuilder::makeArrayNewFixed(HeapType type, uint32_t arity) {
   ArrayNewFixed curr(wasm.allocator);
+  if (!type.isArray()) {
```
Comment (tlively) [inline src/wasm/wasm-ir-builder.cpp:2216]: Is there a reason this has to go here in IRBuilder? It doesn't look like the other allocation instructions have similar checks. I think we normally try to leave this for validation.

Comment (kripken) [reply src/wasm/wasm-ir-builder.cpp:2216]: Oh yeah, the simpler constructors don't have that... I copied this from `makeArrayInitElem`:

https://github.com/WebAssembly/binaryen/blob/2b89d33c7ed8b80cf0ac5223757c47a70f61dcb9/src/wasm/wasm-ir-builder.cpp#L2280-L2282

Is that one also in the wrong place?

Comment (tlively) [reply src/wasm/wasm-ir-builder.cpp:2216]: Hmm, my guess is that we add these guards only when necessary to avoid assertion failures in ChildTyper. Is that what's happening here?

Comment (kripken) [reply src/wasm/wasm-ir-builder.cpp:2216]: Yes, that is the case. Without this PR, the crash is from IRBuilder, long before the validator,
```
(gdb) where
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007ffff329e9ff in __pthread_kill_internal (threadid=<optimized out>, signo=6) at ./nptl/pthread_kill.c:89
#2  0x00007ffff3249cc2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff32324ac in __GI_abort () at ./stdlib/abort.c:73
#4  0x00007ffff3232420 in __assert_fail_base (fmt=<optimized out>, assertion=<optimized out>, file=<optimized out>, line=932, function=<optimized out>) at ./assert/assert.c:118
#5  0x00007ffff6def484 in wasm::HeapType::getArray (this=0x7ffff15c3440) at binaryen/src/wasm/wasm-type.cpp:932
#6  0x00007ffff6d828a4 in wasm::ChildTyper<wasm::IRBuilder::ChildPopper::ConstraintCollector>::visitArrayNewFixed (this=0x7ffff15c3360, curr=0x7ffff168c620) at src/ir/child-typer.h:947
#7  0x00007ffff6d7d24a in wasm::Visitor<wasm::IRBuilder::ChildPopper::ConstraintCollector, void>::visit (this=0x7ffff15c3360, curr=0x7ffff168c620) at src/wasm-delegations.def:89
#8  0x00007ffff6d7c468 in wasm::IRBuilder::ChildPopper::visitExpression (this=0x7ffff1461230, expr=0x7ffff168c620)
    at binaryen/src/wasm/wasm-ir-builder.cpp:579
#9  0x00007ffff6d7c028 in wasm::UnifiedExpressionVisitor<wasm::IRBuilder::ChildPopper, wasm::Result<wasm::Ok> >::visitArrayNewFixed (this=0x7ffff1461230, curr=0x7ffff168c620)
    at src/wasm-delegations.def:89
#10 0x00007ffff6d4f014 in wasm::Visitor<wasm::IRBuilder::ChildPopper, wasm::Result<wasm::Ok> >::visit (this=0x7ffff1461230, curr=0x7ffff168c620) at src/wasm-delegations.def:89
#11 0x00007ffff6d189d6 in wasm::IRBuilder::visitExpression (this=0x7ffff1922130, curr=0x7ffff168c620) at binaryen/src/wasm/wasm-ir-builder.cpp:755
#12 0x00007ffff6d5a928 in wasm::UnifiedExpressionVisitor<wasm::IRBuilder, wasm::Result<wasm::Ok> >::visitArrayNewFixed (this=0x7ffff1922130, curr=0x7ffff168c620)
    at src/wasm-delegations.def:89
#13 0x00007ffff6d406de in wasm::IRBuilder::makeArrayNewFixed (this=0x7ffff1922130, type=..., arity=1) at binaryen/src/wasm/wasm-ir-builder.cpp:2218
...
```
ChildTyper assumes the IR is valid enough for getArray to work, so we must check early.

**Review by tlively — APPROVED** [review]
Makes sense, LGTM.

**Comment by OlivierNicole** [comment]
FYI the bad behaviour still happens with `array.new` instead of `array.new_fixed`.

As far as I unsterstand it probably happens with all array operations.

**Comment by tlively** [comment]
Thanks, all the related problems should be fixed by #7662.
