### PR TITLE
Validate unique local names, and use validation in wasm2js. Fixes #1885

### LINKED ISSUE #1885: Regression testing: Assertion `func->localIndices.size() == func->params.size()' failed.
Hi there,

We did a regression test on previous commits. And we still discovered an Assertion. This probelm was very different to found. Please use "./wasm2js $POC" to reproduce the error.
[POC.zip](https://github.com/WebAssembly/binaryen/files/2787142/POC.zip)

program output
```
Assertion `func->localIndices.size() == func->params.size()' failed.
```

We use the master branch for testing. Git log are shown as follow.
```
commit e63c4a7d04c145dafaf4b09de5f9f5de69cee8ef
Author: Alon Zakai <alonzakai@gmail.com>
Date:   Tue Jan 22 17:15:37 2019 -0800

    More misc ASAN fixes (#1882)

    * fix buffer overflow in simple_ast.h printing.
    * check wasm binary format reading of function export indexes for errors.
    * check if s-expr format imports have a non-empty module and base.

    Fixes #1876
    Fixes #1877
    Fixes #1879
```

Other fixes are very effective, and it's hard to find other problems. Thank you for attention!

### PR DESCRIPTION
**Pull request by kripken**
Also fixes some bugs in wasm2js tests that did not validate.

### CODE REVIEW

File: src/tools/feature-options.h [hunk 1]
```diff
@@ -83,6 +83,11 @@ struct FeatureOptions : public Options {
              [this](Options *o, const std::string& arguments) {
                passOptions.features.setSIMD(false);
              })
+        .add("--no-validation", "-n", "Disables validation, assumes inputs are correct",
```
Comment (dschuff) [inline src/tools/feature-options.h]: It seems odd that this should be a feature option. Is it only here because you want to have it in more than one tool?

**Comment by binji** [comment]
> Just out of curiosity, is the local name requirement only a requirement of Binaryen (since obviously it only has namespaces and not index spaces) or is it also a requirement of the wasm text format?

The text format [requires it](https://webassembly.github.io/spec/core/text/conventions.html#text-context-wf):

> An identifier context is well-formed if no index space contains duplicate identifiers.

But the [custom section does not](https://webassembly.github.io/spec/core/appendix/custom.html):

> Each index must be unique, but the assigned names need not be.

File: src/tools/feature-options.h (hunk 1 above)
Comment (kripken) [reply src/tools/feature-options.h]: Yeah. I agree it's a little odd - this file now means "options for all the tools". I'll rename.
