### PR TITLE
[Custom Descriptors] Fix TypeMerging topological sort

### LINKED ISSUE #7757: Assertion failure in TypeMerging with custom descriptors
```wasm
;; test.wast
(module
  (rec
    (type $A (sub (descriptor $A.desc (struct))))
    (type $A.desc (sub (describes $A (struct))))
    (type $B (sub (descriptor $B.desc (struct))))
    (type $B.desc (sub $A.desc (describes $B (struct))))
  )

  (global $B.desc (ref null $B.desc) (ref.null none))
)
```
`wasm-opt -all --closed-world test.wast --type-merging`

```
wasm-opt: /usr/local/google/home/tlively/code/binaryen/src/support/topological_sort.h:222: wasm::TopologicalOrdersImpl<F>::Selector wasm::TopologicalOrdersImpl<F>::Selector::select(wasm::TopologicalOrdersImpl<F>&) [with Cmp = std::monostate]: Assertion `count >= 1' failed.
```
I have not investigated, but I suppose we must be trying to merge the $B chain into the $A chain even though $B is not a subtype of $A and somehow getting a cycle in a topological sort as a result.

### PR DESCRIPTION
**Pull request by tlively**
TypeMerging uses a topological sort to process supertypes first in
various places. It also treats descriptor chains as single units
represented by their base described type. Types in WebAssembly cannot
have more than one supertype, but the types in a descriptor chain will
have different supertypes and those supertypes may not necessarily be
all in a single descriptor chain together. As a result, when descriptor
chains are treated as units, it is possible for one chain to have
multiple supertype chains. The topological sort in TypeMerging did not
previously take this into account, and as a result the pass tried to
merge types in the wrong order, leading to assertion failures. Fix the
topological sort to correctly treat descriptor chains as units.

Fixes #7757.

### CODE REVIEW

File: src/passes/TypeMerging.cpp [hunk 1]
```diff
@@ -169,13 +168,30 @@ struct TypeMerging : public Pass {
...
+    }
+    // Find the base described type for each supertype in the chain.
+    for (auto [base, _] : subtypes) {
+      for (auto type : base.getDescriptorChain()) {
         if (auto super = type.getDeclaredSuperType()) {
-          return getMerged(*super);
+          auto superBase = getMerged(getBaseDescribedType(*super));
+          if (auto it = subtypes.find(superBase); it != subtypes.end()) {
+            it->second.push_back(base);
+          }
```
Comment (kripken) [inline src/passes/TypeMerging.cpp:191]: I don't follow the comment on this code. "Find the base described type" - but the topmost loop has "base" as a variable, suggesting we immediately loop over the base type? Should that variable be renamed perhaps?

Comment (tlively) [reply src/passes/TypeMerging.cpp:191]: We are looping over the _subtype_ chain starting at `base`, but then we have to find the base described type for each _supertype_, which is `superBase`.

Comment (kripken) [reply src/passes/TypeMerging.cpp:191]: Makes sense, it is just the dual "base" that I find less clear. Perhaps the top loop could be over `descriptorChainBase`?

Comment (tlively) [reply src/passes/TypeMerging.cpp:191]: WDYT of `subBase` to complement `superBase`?

Comment (kripken) [reply src/passes/TypeMerging.cpp:191]: Sounds good. Though maybe also explain in the comment about the two different meanings of "base"?

Comment (tlively) [reply src/passes/TypeMerging.cpp:191]: Done.

Comment (kripken) [reply src/passes/TypeMerging.cpp:191]: Thanks!
