### PR TITLE
Fix issues with Types and Features

### LINKED ISSUE #2770: Fuzz failure on --flatten with "all used types should be allowed"
cc @tlively - looks like it's multivalue related?

```
bin/wasm-opt --all-features --disable-exception-handling a.wasm --flatten
```
[a.wasm.gz](https://github.com/WebAssembly/binaryen/files/4489041/a.wasm.gz)

### PR DESCRIPTION
**Pull request by tlively**
1. Only emit exnref as part of a subtype if exception-handling is
 enabled in the fuzzer.
 2. Correctly report that funcref and nullref require reference-types
 to be enabled.
 3. Re-enable multivalue as a normal feature in the fuzzer.

Possibly fixes #2770.

### CODE REVIEW

File: src/tools/fuzzing.h [hunk 1]
```diff
@@ -327,8 +327,10 @@ class TranslateToFuzzReader {
     options.push_back(type); // includes itself
     switch (type.getSingle()) {
       case Type::anyref:
+        if (wasm.features.hasExceptionHandling()) {
+          options.push_back(Type::exnref);
+        }
         options.push_back(Type::funcref);
```
Comment (kripken) [inline src/tools/fuzzing.h:333]: I assume we don't need to check for reference-types here because the entire function is only called in that case?

Comment (tlively) [reply src/tools/fuzzing.h:333]: I think the function will still be called, but never with `Type::anyref` unless reference types are enabled. This case requires special handling because the subtype needs more features than the supertype.

Comment (kripken) [reply src/tools/fuzzing.h:333]: I see, thanks!

File: src/wasm/wasm-type.cpp [hunk 2]
```diff
@@ -203,7 +203,9 @@ FeatureSet Type::getFeatures() const {
     switch (t.getSingle()) {
       case Type::v128:
         return FeatureSet::SIMD;
+      case Type::funcref:
       case Type::anyref:
+      case Type::nullref:
         return FeatureSet::ReferenceTypes;
       case Type::exnref:
         return FeatureSet::ExceptionHandling;
```
Comment (aheejin) [inline src/wasm/wasm-type.cpp:211]: We probably should change this to `FeatureSet::ReferenceTypes | FeatureSet::ExceptionHandling` too

Comment (tlively) [reply src/wasm/wasm-type.cpp:211]: Sounds good, will do. Is it possible to use exception handling at all if reference types is not enabled?

Comment (aheejin) [reply src/wasm/wasm-type.cpp:211]: No. But we currently don't have a way to express feature dependencies in Binaryen, so I'm using `FeatureSet::ReferenceTypes | FeatureSet::ExceptionHandling` wherever I use `FeatureSet::ExceptionHandling`.

I think we once talked about this feature dependencies thing several months ago (which felt like ages ago now), and kind of decided that we take care of that in clang and features section.
