### PR TITLE
DWARF: Fix debug_info references to the abbreviations section

### LINKED ISSUE #2992: wasm-opt crashing with "uncaught exception of type std::out_of_range: unordered_map::at: key not found"
Repro steps:

1. Download and unzip [wasm-opt-crash.zip](https://github.com/WebAssembly/binaryen/files/4984161/wasm-opt-crash.zip)
2. Setup emscripten sdk version 1.39.20
3. Run the following command:

```bash
emcc --profiling-funcs -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s BINARYEN=1 -s ALIASING_FUNCTION_POINTERS=0 -s NO_EXIT_RUNTIME=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'FS_createPath', 'FS_createDataFile', 'cwrap', 'setValue', 'getValue', 'UTF8ToString', 'UTF8ArrayToString', 'addFunction']" -s "EXPORTED_FUNCTIONS=['_putchar']" --source-map-base http://example.com  -emit-llvm -s FORCE_FILESYSTEM=1 -s USE_ZLIB=1 -g -O2 -s ASSERTIONS=1 -DENABLE_NETCORE=1 -DDEBUG=1 --js-library library_mono.js --js-library binding_support.js --js-library dotnet_support.js libSystem.IO.Compression.Native.a libSystem.Native.a libicudata.a libicui18n.a libicuuc.a libmono-ee-interp.a libmono-icall-table.a libmono-ilgen.a libmonosgen-2.0.a corebindings.o driver.o pinvoke.o -o dotnet.js
```

It crashes with the following error:

```
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: unordered_map::at: key not found
emcc: error: '/Users/alexander/dev/emsdk/upstream/bin/wasm-opt --post-emscripten --no-exit-runtime -O2 --low-memory-unused --strip-producers --pass-arg=stack-pointer@5883312 --pass-arg=emscripten-sbrk-ptr@640272 dotnet.wasm -o dotnet.wasm -g --mvp-features' failed (-6)
```

@sbc100 mentioned that this is most likely a binaryen issue.

### LINKED ISSUE #3007: Instrumenting wasm binary fails with: compile unit size was incorrect
This look related to this issue: https://github.com/WebAssembly/binaryen/issues/2673

I use the following command:
```
wasm-opt --log-execution test.wasm -o test.instrumented.wasm
```

I tried it with version 94 & 95 and it fails. Downgrading to version 90 makes it work.

With version 94 & 95 I get the following output:
```
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 17 (range: 1 : 28..33)
warning: invalid abbreviation code 17 (range: 1 : 28..33)
warning: invalid abbreviation code 17 (range: 1 : 28..33)
warning: invalid abbreviation code 17 (range: 1 : 28..33)
warning: invalid abbreviation code 17 (range: 1 : 28..33)
warning: invalid abbreviation code 17 (range: 1 : 28..33)
warning: invalid abbreviation code 17 (range: 1 : 28..33)
warning: invalid abbreviation code 16 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 18 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 20 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 20 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 17 (range: 1 : 28..33)
warning: invalid abbreviation code 15 (range: 1 : 28..33)
warning: invalid abbreviation code 18 (range: 1 : 28..33)
warning: invalid abbreviation code 21 (range: 1 : 28..33)
warning: invalid abbreviation code 15 (range: 1 : 28..33)
warning: invalid abbreviation code 18 (range: 1 : 28..33)
warning: invalid abbreviation code 16 (range: 1 : 28..33)
warning: invalid abbreviation code 20 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 20 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 20 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 20 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 20 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 21 (range: 1 : 28..33)
warning: invalid abbreviation code 21 (range: 1 : 28..33)
warning: invalid abbreviation code 21 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 15 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 15 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 20 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 21 (range: 1 : 28..33)
warning: invalid abbreviation code 21 (range: 1 : 28..33)
warning: invalid abbreviation code 21 (range: 1 : 28..33)
warning: invalid abbreviation code 21 (range: 1 : 28..33)
warning: invalid abbreviation code 21 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 21 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 22 (range: 1 : 28..33)
warning: invalid abbreviation code 21 (range: 1 : 28..33)
warning: invalid abbreviation code 15 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 22 (range: 1 : 28..33)
warning: invalid abbreviation code 21 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 7 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 16 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 16 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 23 (range: 1 : 28..33)
warning: invalid abbreviation code 15 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 24 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 15 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 20 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 20 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 24 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 15 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 25 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 26 (range: 1 : 28..33)
warning: invalid abbreviation code 16 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 16 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 27 (range: 1 : 28..33)
warning: invalid abbreviation code 20 (range: 1 : 28..33)
warning: invalid abbreviation code 27 (range: 1 : 28..33)
warning: invalid abbreviation code 20 (range: 1 : 28..33)
warning: invalid abbreviation code 27 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 13 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 13 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 24 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 22 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 13 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 13 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 13 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 17 (range: 1 : 28..33)
warning: invalid abbreviation code 21 (range: 1 : 28..33)
warning: invalid abbreviation code 21 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 17 (range: 1 : 28..33)
warning: invalid abbreviation code 16 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 15 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 20 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 12 (range: 1 : 28..33)
warning: invalid abbreviation code 10 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 8 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 19 (range: 1 : 28..33)
warning: invalid abbreviation code 14 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
warning: invalid abbreviation code 15 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 15 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 9 (range: 1 : 28..33)
warning: invalid abbreviation code 11 (range: 1 : 28..33)
warning: invalid abbreviation code 6 (range: 1 : 28..33)
compile unit size was incorrect
UNREACHABLE executed at /build/source/third_party/llvm-project/DWARFEmitter.cpp:196!
Aborted (core dumped)
```

The wasm file can be found here: https://gofile.io/d/liXPa9

### PR DESCRIPTION
**Pull request by kripken**
The previous code assumed that each compile unit had its own
abbreviation section, and they are all in order. That's normally how
LLVM emits things, but in #2992 there is a testcase in which linking
of object files with IR files somehow ends up with a different order.

The proper fix is to track the binary offsets of abbreviations in the
abbreviation section. That section is comprised of null-terminated
lists, which each CU has an offset to the beginning of. With those
offsets, we can match things properly.

Add a testcase that crashes without this, to prevent regressions. 

Fixes #2992 
Fixes #3007

### CODE REVIEW

File: third_party/llvm-project/DWARFVisitor.cpp [hunk 1]
```diff
@@ -44,17 +44,26 @@ static unsigned getRefSize(const DWARFYAML::Unit &Unit) {
...
   // so that lookups are linear. In LLVM output that is true, but it might not
   // be in general.
-  size_t AbbrevStart = 0, AbbrevEnd = -1;
   for (auto &Unit : DebugInfo.CompileUnits) {
-    // Skip the 0 terminator.
-    AbbrevEnd = AbbrevStart = AbbrevEnd + 1;
+    // AbbrOffset is the byte offset into the abbreviation section, which we
+    // need to find among the Abbrev's ListOffsets (which are the byte offsets
+    // of where that abbreviation list begins).
+    // TODO: Optimize this to not be O(#CUs * #abbrevs).
```
Comment (dschuff) [inline third_party/llvm-project/DWARFVisitor.cpp:56]: Would it make sense to optimize for the common case of the lists being sorted by CU? e.g. save the previous position and start there rather than starting from 0 each time?

Comment (kripken) [reply third_party/llvm-project/DWARFVisitor.cpp:56]: Yeah, that might make sense. Or a full mapping, that would be constant time in all cases. I'll look into it as a followup.
