### PR TITLE
Fix TypeComparator to satisfy C++'s Compare requirement

### LINKED ISSUE #3648: Strange issue with std::map<Type, ..>
In `wasm-stack` we have `std::map<Type, size_t> numLocalsByType;`. On the testcase below something quite odd happens, on this code:
```cpp
  o << U32LEB(numLocalsByType.size());
  for (auto& typeCount : numLocalsByType) {
    o << U32LEB(typeCount.second);
    parent.writeType(typeCount.first);
  }
```
That writes the number of types on the first line, and then the type count and ID for each one. But while `.size()` reports 3, the loop only goes through 2 iterations.

This is not iterator invalidation. Removing the inner lines in the loop have no effect. (Also ubsan and asan find nothing.)

There is basically a divergence between the reported size of the container and the observed contents when iterating. Is there any situation in which that is expected to happen?

My only theory is some weirdness related to canonicalization of Types, that is, somehow 2 of the 3 keys in the map are seen as identical to each other, and we just iterate on those...? (but that doesn't seem to make sense) cc @tlively 

Testcase:
```wat
(module
 (type $a (func (param (ref null $b))))
 (type $b (struct (field (ref null $i))))
 (type $c (struct (field (ref null $l))))
 (type $d (func (param (ref null $b))))
 (type $e (func (result (ref null $g))))
 (type $f (func (result (ref null $c))))
 (type $g (struct (field (ref null $j))))
 (type $h (struct (field (ref null $k))))
 (type $i (struct (field (mut (ref null $a)))))
 (type $j (struct (field (mut (ref null $a))) (field (mut (ref null $a)))))
 (type $k (struct (field (mut (ref null $a))) (field (mut (ref null $a))) (field (mut (ref null $e)))))
 (type $l (struct (field (mut (ref null $a))) (field (mut (ref null $d))) (field (mut (ref null $f)))))

 (func $foo
  (local $1 (ref null $h))
  (local $2 (ref null $b)) ;; moving this line one down or up avoids the bug
  (local $3 (ref null $c))
 )
)
```
`wasm-opt a.wat  -all --roundtrip` will throw an exception when trying to read after writing an in-memory binary. (can also write to a file and read from there)

### PR DESCRIPTION
**Pull request by tlively**
The comparison implemented by TypeComparator was not previously antisymmetric
because it held that both A < B and B < A when A and B were structurally
identical but nominally distinct recursive types. This meant that it did not
satisfy the conditions of C++'s "Compare" requirement, which meant that std::set
did not operate correctly, as discovered in #3648. The PR fixes the problem by
having making A < B be false (and vice versa), making type comparisons properly
antisymmetric.

As a drive by, also switches to using std::stable_sort in collectHeapTypes to
make the order of the type section completely deterministic accross platforms.

Fixes #3648.

### CODE REVIEW

**Comment by tlively** [comment]
After spending a few hours writing deterministic replacements for std::set and std::map and pulling out the use of type comparisons everywhere, I realized this was actually just a one line fix 🙃

File: src/wasm/wasm-type.cpp [hunk 1]
```diff
@@ -858,9 +858,9 @@ bool TypeComparator::lessThan(HeapType a, HeapType b) {
     return false;
   }
   if (seen.count({a, b})) {
-    // We weren't able to disprove that a < b since we last saw them, so the
-    // relation holds coinductively.
-    return true;
+    // We weren't able to disprove that a == b since we last saw them, so it
+    // holds coinductively. a < b is therefore false;
+    return false;
```
Comment (kripken) [inline src/wasm/wasm-type.cpp:863]: It's not obvious to me why this is enough, but maybe I don't know the C++ spec well enough. Do you have a link?

My intuition is that before you could have `a < b, b < a, a != b`, while now you will have `a >= b, b >= a, a != b` which from a logical point of view is equivalent.

Comment (tlively) [reply src/wasm/wasm-type.cpp:863]: https://en.cppreference.com/w/cpp/named_req/Compare. The key point is that it _only_ requires < to create a weak ordering and it's ok if == is not consistent with that ordering.

File: src/wasm/wasm-type.cpp [hunk 2]
```diff
@@ -858,9 +858,9 @@ bool TypeComparator::lessThan(HeapType a, HeapType b) {
     return false;
   }
   if (seen.count({a, b})) {
-    // We weren't able to disprove that a < b since we last saw them, so the
-    // relation holds coinductively.
-    return true;
+    // We weren't able to disprove that a == b since we last saw them, so it
+    // holds coinductively. a < b is therefore false;
```
Comment (kripken) [inline src/wasm/wasm-type.cpp:862]:
```suggestion
    // holds coinductively that a < b is therefore false.
```

File: src/wasm/wasm-type.cpp (hunk 1 above)
Comment (kripken) [reply src/wasm/wasm-type.cpp:863]: I see, thanks! So yes, it must be a strict weak ordering, and so `!(a < b), !(b < a), a != b` is fine.

**Review by kripken — APPROVED** [review]

**Comment by tlively** [comment]
I manually force-merged this because the alpine tests seemed to be hanging :/
