### PR TITLE
Costs: Adjust the cost of calls

### LINKED ISSUE #8044: Functions with `call.without.effects` should preserve their conditions.
Right now, Binaryen optimizes this:
```WAT
local.get $condition
if (result i32)
    local.get $argument
    ref.func $my_func ;; my_func (param i32) (result i32)
    call $call.without.effects
else
    i32.const 0
end
```

Into this:

```WAT
local.get $condition
local.get $argument
call $my_func  ;; my_func (param i32) (result i32)
i32.const 0
select
```

Before, the function was only called if `$condition` but the optimizer has made the call unconditional. I can think of two situations this is harmful:

1. If the call to the function is expensive. Getting rid of the conditional execution means binaryen will eliminate any faster paths trying to avoid the call.
2. If the call to the function may have effects when the condition is not kept. For example, a function which crashes for inputs less than 0 might be guarded by a check to make sure the input is less than 0, avoiding the call if so. This call can still be removed if the result is dropped (because it has no other effects), but the condition must not be removed.

I have run into both of these cases trying to implement `call.without.effects` into my compiler. I was advised to make this into it's own issue from my comment on [#7574](https://github.com/WebAssembly/binaryen/issues/7574#issuecomment-3509633176).

### PR DESCRIPTION
**Pull request by kripken**
The cost of "4" earlier was in place because call costs don't really matter
(the effects prevent removing/replacing them), but there are calls without
effects, like with the proper intrinsic. Model call costs as very expensive.

The monomorphize test change is because it has hardcoded costs, and
calls are now too "heavy" for what it wants. The calls are replaced by
other code that does a bunch of work.

Fixes #8044

### CODE REVIEW

File: src/ir/cost.h [hunk 1]
```diff
@@ -68,23 +74,23 @@ struct CostAnalyzer : public OverriddenVisitor<CostAnalyzer, CostType> {
...
-    CostType ret = 4;
+    CostType ret = CallCost;
     for (auto* child : curr->operands) {
       ret += visit(child);
     }
     return ret;
   }
   CostType visitCallIndirect(CallIndirect* curr) {
-    CostType ret = 6 + visit(curr->target);
+    // Model indirect calls as more expensive than call_refs.
```
Comment (tlively) [inline src/ir/cost.h]: I don't think this is accurate on V8, at least, because function tables are privileged in some special way that actually makes call_indirect faster than call_ref even though it does more work semantically. Let's just give them the same cost here.

Comment (kripken) [reply src/ir/cost.h]: Done.

**Review by tlively — APPROVED** [review]
