### PR TITLE
Store HeapTypes in Tags

### LINKED ISSUE #7219: Binaryen changes type structure in open world even with zero-level optimization enabled
It seems passing a `.wasm` file could change types structure for exported tag.

I use this command to optimise attached example which originally works fine:

`wasm-opt --enable-gc --enable-reference-types --enable-exception-handling --enable-bulk-memory --enable-nontrapping-float-to-int --inline-functions with-loops --traps-never-happen --fast-math stdlib.wasm -o xxx.wasm`

And get this warning: `no passes specified, not doing any work`, but nevertheless, when I replace `stdlib.wasm` with `xxx.wasm` and reload app to use optimised `.wasm` file I get

`LinkError: WebAssembly.instantiate(): Import #74 "stdlib" "tag_throwable": imported tag does not match the expected type`
So seems binaryen rewrite exported tag type so it cannot be imported.

Reproduced on binaryen 121 and [current master]
[binaryen_bug.zip](https://github.com/user-attachments/files/18425504/binaryen_bug.zip)

### PR DESCRIPTION
**Pull request by tlively**
Tags in WebAssembly syntactically refer to function heap types, but
Binaryen IR was previously storing signatures instead and reconstructing
heap types as necessary when emitting binaries. Before WasmGC this was
not a problem because the reconstructed types would be the same as the
original types, but with WasmGC round tripping function types through
Signature could lose information such as the rec group, the declared
supertype, and the finality from the original type. Store the original
heap type in the IR instead to stop losing this information.

Fixes #7219.

### CODE REVIEW

File: src/wasm.h [hunk 1]
```diff
@@ -2297,7 +2297,9 @@ class Global : public Importable {
 
 class Tag : public Importable {
 public:
-  Signature sig;
+  HeapType type;
+  Type params() { return type.getSignature().params; }
```
Comment (kripken) [inline src/wasm.h:2301]:
```suggestion

    Type params() { return type.getSignature().params; }
```
(just to separate properties from methods, which we generally do)

File: src/passes/Print.cpp [hunk 2]
```diff
@@ -3185,32 +3186,41 @@ void PrintSExpression::visitImportedTag(Tag* curr) {
...
   curr->name.print(o);
-  if (curr->sig.params != Type::none) {
-    o << maybeSpace;
-    printParamType(curr->sig.params);
+  o << maybeSpace;
+  printTagType(curr->type);
+  o << ')' << maybeNewLine;
+}
+
+void PrintSExpression::printTagType(HeapType type) {
```
Comment (kripken) [inline src/passes/Print.cpp:3204]: Looks like `handleSignature` (used for Function) is similar - can we share this code perhaps?

**Review by kripken — COMMENTED** [review]
lgtm % comments

File: src/passes/Print.cpp (hunk 2 above)
Comment (tlively) [reply src/passes/Print.cpp:3204]: I'll take another look at it. At first glance the existence of parameter names for functions made it seem writing separate code.

Comment (tlively) [reply src/passes/Print.cpp:3204]: Yep, I think it's more trouble than it's worth right now.

**Review by aheejin — APPROVED** [review]

**Review by kripken — APPROVED** [review]
