### PR TITLE
Fix asm2wasm unsigned float-to-int

### LINKED ISSUE #974: asm2wasm floating point trap
https://github.com/kripken/emscripten/pull/5134 exposed a test failure on the wasm waterfall (https://wasm-stat.us/builders/linux/builds/18571/steps/Execute%20LLVM%20Torture%20%28asm2wasm%29/logs/stdio), compiling gcc's `conversion.c` torture test.

Pared down input file (compiled with `emcc -O0`):
```c
#include <stdlib.h>

unsigned int f2u(float f) {
  return (unsigned)f;
}

int main() {
  if (f2u((float)~((~0U) >> 1)) != ~((~0U) >> 1)) { /* 0x80000000 */
    abort();
  }
  exit(0);
}
```
This causes V8 and SM to throw a runtime exception due to integer overflow.
The relevant `asm2wasm`+`wasm2wast` output looks like:
```
  (func _f2u (type 7) (param f32) (result i32)
    (local i32 i32 i32 f32 f32)
    block i32  ;; label = @1
      get_global 12
      set_local 3
      get_global 12
      i32.const 16
      i32.add
      set_global 12
      get_global 12
      get_global 13
      i32.ge_s
      if  ;; label = @2
        i32.const 16
        call abortStackOverflow
      end
      get_local 0
      set_local 5
      get_local 5
      set_local 4
      get_local 4
      i32.trunc_s/f32
      set_local 1
      get_local 3
      set_global 12
      get_local 1
      return
      unreachable
    end)
```
Of particular note is the `i32.trunc_s/f32` instruction, which should be an `i32.trunc_u/f32`. The problem is we're trying to put `1 << 31` into a signed int, when we really want to put it into an unsigned int.

### PR DESCRIPTION
**Pull request by kripken**
Fixes #974.

### CODE REVIEW

File: src/asm2wasm.h [hunk 1]
```diff
@@ -735,11 +735,12 @@ class Asm2WasmBuilder {
   }
 
   // Some conversions might trap, so emit them safely if necessary
-  Expression* makeTrappingFloatToInt(Expression* value) {
+  Expression* makeTrappingFloatToInt(bool signed_, Expression* value) {
     if (trapMode == TrapMode::Allow) {
       auto ret = allocator.alloc<Unary>();
       ret->value = value;
-      ret->op = ret->value->type == f64 ? TruncSFloat64ToInt32 : TruncSFloat32ToInt32;
+      ret->op = signed_ ? (ret->value->type == f64 ? TruncSFloat64ToInt32 : TruncSFloat32ToInt32)
```
Comment (jgravelle-google) [inline src/asm2wasm.h]: Nit: Nested ternary expressions are generally unfriendly to read. Though this one isn't too bad, breaking this into an `if`/`else` might be more quickly scannable.

Nit: Mild repetition of `ret->value->type == f64`, maybe promote to a `bool isDouble`?

Comment (kripken) [inline src/asm2wasm.h]: Makes sense, updated.
