### PR TITLE
Fix ExceptionPackage memory errors

### LINKED ISSUE #3087: Memory leak in Literal
Pinning this here so we don't forget: An `exnref` `Literal`'s `std::unique_ptr<ExceptionPackage> exn`  (part of the union) is leaky in that it is not destroyed upon copy assignment (if I'm not mistaken).

Steps to reproduce:

* Compile with `-fsanitize=address`
* Run `wasm-shell test/spec/exception-handling.wast`

```
==7466==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 256 byte(s) in 4 object(s) allocated from:
    #0 0x7f8563cb4947 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10f947)
    #1 0x7f8562fa3291 in wasm::Literal::operator=(wasm::Literal const&) (/path/to/binaryen/lbuild/bin/../lib/libbinaryen.so+0x1382291)
    #2 0x56542f4eb7bd in wasm::SmallVector<wasm::Literal, 1ul>::SmallVector(wasm::SmallVector<wasm::Literal, 1ul> const&) (/path/to/binaryen/lbuild/bin/wasm-shell+0x3e7bd)
    #3 0x56542f545ad4 in wasm::OverriddenVisitor<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner, wasm::Flow>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x98ad4)
    #4 0x56542f54a284 in wasm::ExpressionRunner<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x9d284)
    #5 0x56542f5454be in wasm::OverriddenVisitor<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner, wasm::Flow>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x984be)
    #6 0x56542f54a284 in wasm::ExpressionRunner<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x9d284)
    #7 0x56542f5468a6 in wasm::OverriddenVisitor<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner, wasm::Flow>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x998a6)
    #8 0x56542f58410f in wasm::ExpressionRunner<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner>::visitBlock(wasm::Block*) (/path/to/binaryen/lbuild/bin/wasm-shell+0xd710f)
    #9 0x56542f546828 in wasm::OverriddenVisitor<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner, wasm::Flow>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x99828)
    #10 0x56542f58410f in wasm::ExpressionRunner<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner>::visitBlock(wasm::Block*) (/path/to/binaryen/lbuild/bin/wasm-shell+0xd710f)
    #11 0x56542f546828 in wasm::OverriddenVisitor<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner, wasm::Flow>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x99828)
    #12 0x56542f54a284 in wasm::ExpressionRunner<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x9d284)
    #13 0x56542f54a0cb in wasm::OverriddenVisitor<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner, wasm::Flow>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x9d0cb)
    #14 0x56542f54a284 in wasm::ExpressionRunner<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x9d284)
    #15 0x56542f54ac79 in wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::callFunctionInternal(wasm::Name, std::vector<wasm::Literal, std::allocator<wasm::Literal> > const&) (/path/to/binaryen/lbuild/bin/wasm-shell+0x9dc79)
    #16 0x56542f4e3cc8 in run_asserts(wasm::Name, unsigned long*, bool*, wasm::Module*, wasm::Element*, wasm::SExpressionWasmBuilder*, wasm::Name) (/path/to/binaryen/lbuild/bin/wasm-shell+0x36cc8)
    #17 0x56542f4ce1b4 in main (/path/to/binaryen/lbuild/bin/wasm-shell+0x211b4)
    #18 0x7f856185a0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f8563cb4947 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10f947)
    #1 0x7f8562fa3434 in wasm::Literal::operator=(wasm::Literal const&) (/path/to/binaryen/lbuild/bin/../lib/libbinaryen.so+0x1382434)
    #2 0x56542f4eb7bd in wasm::SmallVector<wasm::Literal, 1ul>::SmallVector(wasm::SmallVector<wasm::Literal, 1ul> const&) (/path/to/binaryen/lbuild/bin/wasm-shell+0x3e7bd)
    #3 0x56542f545ad4 in wasm::OverriddenVisitor<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner, wasm::Flow>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x98ad4)
    #4 0x56542f54a284 in wasm::ExpressionRunner<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x9d284)
    #5 0x56542f5454be in wasm::OverriddenVisitor<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner, wasm::Flow>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x984be)
    #6 0x56542f54a284 in wasm::ExpressionRunner<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x9d284)
    #7 0x56542f5468a6 in wasm::OverriddenVisitor<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner, wasm::Flow>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x998a6)
    #8 0x56542f58410f in wasm::ExpressionRunner<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner>::visitBlock(wasm::Block*) (/path/to/binaryen/lbuild/bin/wasm-shell+0xd710f)
    #9 0x56542f546828 in wasm::OverriddenVisitor<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner, wasm::Flow>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x99828)
    #10 0x56542f58410f in wasm::ExpressionRunner<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner>::visitBlock(wasm::Block*) (/path/to/binaryen/lbuild/bin/wasm-shell+0xd710f)
    #11 0x56542f546828 in wasm::OverriddenVisitor<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner, wasm::Flow>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x99828)
    #12 0x56542f54a284 in wasm::ExpressionRunner<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x9d284)
    #13 0x56542f54a0cb in wasm::OverriddenVisitor<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner, wasm::Flow>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x9d0cb)
    #14 0x56542f54a284 in wasm::ExpressionRunner<wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::RuntimeExpressionRunner>::visit(wasm::Expression*) (/path/to/binaryen/lbuild/bin/wasm-shell+0x9d284)
    #15 0x56542f54ac79 in wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literals, std::less<wasm::Name>, std::allocator<std::pair<wasm::Name const, wasm::Literals> > >, wasm::ModuleInstance>::callFunctionInternal(wasm::Name, std::vector<wasm::Literal, std::allocator<wasm::Literal> > const&) (/path/to/binaryen/lbuild/bin/wasm-shell+0x9dc79)
    #16 0x56542f4e3cc8 in run_asserts(wasm::Name, unsigned long*, bool*, wasm::Module*, wasm::Element*, wasm::SExpressionWasmBuilder*, wasm::Name) (/path/to/binaryen/lbuild/bin/wasm-shell+0x36cc8)
    #17 0x56542f4ce1b4 in main (/path/to/binaryen/lbuild/bin/wasm-shell+0x211b4)
    #18 0x7f856185a0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: 280 byte(s) leaked in 5 allocation(s).
```

Unfortunately, my attempts to fix this have failed so far, leading to even more obscure use-after-free kind of errors. Requesting expert support :)

### PR DESCRIPTION
**Pull request by tlively**
First, adds an explicit destructor call to fix a memory leak in
`Literal::operator=` in which existing `ExceptionPackage`s would be
silently dropped. Next, changes `Literal::getExceptionPackage` to
return the `ExceptionPackage` by value to avoid a use-after-free bug
in the interpreter that was surfaced by the new destructor call.

Fixes #3087.

### CODE REVIEW

File: src/wasm/literal.cpp [hunk 1]
```diff
@@ -54,7 +57,9 @@ Literal& Literal::operator=(const Literal& other) {
       func = other.func;
       break;
     case Type::exnref:
-      new (&exn) auto(std::make_unique<ExceptionPackage>(*other.exn));
+      // Avoid calling the destructor, which may not be correct
+      new (&exn) auto(
+        std::move(std::make_unique<ExceptionPackage>(*other.exn)));
```
Comment (tlively) [inline src/wasm/literal.cpp:62]: This was already not calling the destructor; the addition of `std::move` is just a drive-by optimization.

It is important to _not_ call the destructor if the previous type was anything besides `exnref`, so this line was already correct. The only thing missing was that we had to call the destructor if the previous type _was_ `exnref`.

Comment (tlively) [reply src/wasm/literal.cpp:62]: This is one of those days where I think longingly of Rust 🦀

**Comment by dcodeIO** [comment]
Looking at your fix (yay!), this somewhat reminds me of

https://github.com/WebAssembly/binaryen/blob/fecfa92d71633f8bb28bb97a60adc9b54998456f/src/wasm-interpreter.h#L68-L71

which is passing a literal by reference. Just curious if this might be problematic, or is this fine?

**Comment by dcodeIO** [comment]
(just gave this a shot, and indeed removing just the `&` in the code snippet above also makes the sanitizer pass, at least in my branch with the destructor call uncommented. I'm fascinated.)

**Comment by tlively** [comment]
> Looking at your fix (yay!), this somewhat reminds me of
> 
> https://github.com/WebAssembly/binaryen/blob/fecfa92d71633f8bb28bb97a60adc9b54998456f/src/wasm-interpreter.h#L68-L71
> 
> which is (pretty much the only occasion not in literal.h/cpp) passing a literal by reference. Just curious if this might be problematic, or is this fine?

This is fine as long as the reference returned by this function is never used after the underlying `Literals` is destroyed. So every caller just has to be careful and not mess up. It would be safer to return the `Literal` by value rather than by reference, but then we would be making unnecessary copies all over the place.

In Rust, we would have to add a lifetime annotation to this function in order to return the reference, but in return the type system would guarantee that the reference would never be dangling.

**Comment by dcodeIO** [comment]
In modern times an idiom has grown from it meaning "Any source of great and unexpected troubles", or alternatively "A present which seems valuable but which in reality is a curse".

What is _______ ?

**Comment by tlively** [comment]
Omg, now the issue is that the copy constructor is implemented in terms of the assignment operator, but the assignment operator now reads from the current value of `Literal::type`, which is of course uninitialized, so this is UB.

This is quite the pandora's box ;)

**Comment by dcodeIO** [comment]
Not sure if related, but though I check out your branch, compile with `-fsanitize=address` and run check.py before approving, which found

```
.. flatten_dfo_O3_enable-threads.wast
executing:  /path/to/binaryen/lbuild/bin/wasm-opt --flatten --dfo -O3 --enable-threads split.wast --print
warning: no output file specified, not emitting output

=================================================================
==4718==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 8208 byte(s) in 18 object(s) allocated from:
    #0 0x7f59a7b48947 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10f947)
    #1 0x7f59a6349fff in wasm::DataFlowOpts::optimizeExprToConstant(wasm::DataFlow::Node*) (/path/to/binaryen/lbuild/bin/../lib/libbinaryen.so+0x895fff)
    #2 0x7f59a6350b2c in wasm::DataFlowOpts::doWalkFunction(wasm::Function*) (/path/to/binaryen/lbuild/bin/../lib/libbinaryen.so+0x89cb2c)
    #3 0x7f59a6352ccd in wasm::WalkerPass<wasm::PostWalker<wasm::DataFlowOpts, wasm::Visitor<wasm::DataFlowOpts, void> > >::runOnFunction(wasm::PassRunner*, wasm::Module*, wasm::Function*) (/path/to/binaryen/lbuild/bin/../lib/libbinaryen.so+0x89eccd)
    #4 0x7f59a60a406c in wasm::PassRunner::runPassOnFunction(wasm::Pass*, wasm::Function*) (/path/to/binaryen/lbuild/bin/../lib/libbinaryen.so+0x5f006c)
    #5 0x7f59a60a4f2e in std::_Function_handler<wasm::ThreadWorkState (), wasm::PassRunner::run()::{lambda()#2}::operator()() const::{lambda()#1}>::_M_invoke(std::_Any_data const&) (/path/to/binaryen/lbuild/bin/../lib/libbinaryen.so+0x5f0f2e)
    #6 0x7f59a7245091 in wasm::Thread::mainLoop(void*) (/path/to/binaryen/lbuild/bin/../lib/libbinaryen.so+0x1791091)
    #7 0x7f59a7246849 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(void*), wasm::Thread*> > >::_M_run() (/path/to/binaryen/lbuild/bin/../lib/libbinaryen.so+0x1792849)
    #8 0x7f59a59a9cb3  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd6cb3)

SUMMARY: AddressSanitizer: 8208 byte(s) leaked in 18 allocation(s).
```

Makes me wonder if we should add AddressSanitizer to CI?

**Comment by tlively** [comment]
We already have ASan on CI, but we disable the leak checker, probably because all our leaks would cause our CI to fail! It would certainly be good to clean up the remaining leaks and enable leak checking on CI.

**Comment by tlively** [comment]
To be clear, I think this PR is good to land, though. That other leak can be cleaned up separately.

**Comment by aheejin** [comment]
Come to think of it, I'm not sure if we should use `unique_ptr` in the first place. `Literal`s are copied everywhere, when they are stored in `Flow`s and retrieved. For example, here, I don't think we want to make the stored version of `ExceptionPackage`. This looks fine at the moment because it returns a reference, but does this mean we consider `Flow` as a canonical storage for `Literal`s?

Can't we just make this `shared_ptr` and pass `Literal`s by value anywhere, to make matters simple? I'm actually trying this myself, but this gives me another leak, so I was debugging it, but I now have to leave for today. #3087 says `shared_ptr` doesn't work because it increases the union size, which I don't understand, because we have `uint8_t v128[16];` in that union anyway. I changed `unique_ptr` to `shared_ptr` and I didn't have any problem compiling the whole program.

**Comment by tlively** [comment]
> does this mean we consider `Flow` as a canonical storage for `Literal`s?

That's how I've been thinking about it.

> Can't we just make this `shared_ptr` and pass `Literal`s by value anywhere, to make matters simple?

It seems slightly simpler to me to use `unique_ptr` and just copy the payload as necessary. That would have the benefit that a `Literal` would be the sole owner of its payload, so it would be safe to mutate the payload. But I don't feel strongly about it.

`getSingleValue` only returns a reference because it is essentially a shortcut for `flow.values[0]` with an assert, but I agree that `Literal`s should be passed by value in most situtations.

**Comment by dcodeIO** [comment]
Hmm I don't recall exactly why `shared_ptr` didn't just work, but I remember that the assert in `binaryen-c.cpp` comparing both `Literal` and `BinaryenLiteral` to have the same size triggered. Might well be that I did something else wrong leading to it, was trying out lots of stuff at that point. In general I think that if a `Literal` remains the sole owner of its payload anyway, we might just use an `ExceptionPackage*` that we `new` and `delete`, greatly simplifying the code as I don't see what benefit `unique_ptr` gives us if we have to `exn.~unique_ptr()` it explicitly anyway.

**Comment by tlively** [comment]
> In general I think that if a `Literal` remains the sole owner of its payload anyway, we might just use an `ExceptionPackage*` that we `new` and `delete`, greatly simplifying the code as I don't see what benefit `unique_ptr` gives us if we have to `exn.~unique_ptr()` it explicitly anyway.

Hmm, good point. Even if it feels dangerous, it's actually the same as using a unique_ptr in this case. Of course one way to actually make this safer would be to upgrade to C++17 and use a std::variant instead of manually managing a union here. Maybe that would be worth doing soonish...

File: src/literal.h [hunk 2]
```diff
@@ -135,10 +135,7 @@ class Literal {
     assert(type == Type::funcref);
     return func;
   }
-  const ExceptionPackage& getExceptionPackage() const {
-    assert(type == Type::exnref);
-    return *exn.get();
-  }
+  ExceptionPackage getExceptionPackage() const;
```
Comment (kripken) [inline src/literal.h:138]: why move this body to the cpp? all the siblings are here it seems.

Comment (tlively) [reply src/literal.h:138]: Since `ExceptionPackage` is now returned by value, it needs to be a complete type at the point of this function definition. But the definition of `ExceptionPackage` can't move before the definition of `Literal` for the same reason, so the only choice was to move `getExceptionPackage` to be defined out of line, which means it needs to be in the .cpp file.

**Comment by tlively** [comment]
Cool, I'll land this as-is (even though the unique_ptr doesn't buy us much) for now and we can revisit this and probably make `Literal` a `std::variant` later.

File: src/literal.h (hunk 2 above)
Comment (kripken) [reply src/literal.h:138]: I see, thanks...

**Comment by kripken** [comment]
+1 for doing c++17 sooner than later in order to use `std::variant`!

**Comment by aheejin** [comment]
Sorry, I think using `unique_ptr` is actually dangerous and a source of potential bugs. `Literal` is not only used in the interpreter, and it is copied every single time it is created and passed. It is pure luck that we only use `Literal` for `exnref` in the interpreter. Making `Flow` as a canonical source of `Literal` has not been discussed so far, and that doesn't hold true for `Literal`s outside of the interpreter anyway.

**Comment by aheejin** [comment]
> Hmm I don't recall exactly why `shared_ptr` didn't just work, but I remember that the assert in `binaryen-c.cpp` comparing both `Literal` and `BinaryenLiteral` to have the same size triggered. 

I didn't have any problem with this clause.

**Comment by kripken** [comment]
@aheejin I agree `unique_ptr` is not good here. This PR looks like a good incremental step though, as it doesn't add `unique_ptr`, and improves what we have already. But yes, let's move towards avoiding `unique_ptr` here entirely.

**Comment by aheejin** [comment]
Yeah, using it was my fault in the first place ;( But anyway, it will likely to be gone at some point.
