### PR TITLE
Properly error on multivalue returns in GenerateDynCalls

### LINKED ISSUE #5586: Aborted in wasm::getSig(wasm::Type, wasm::Type) at asmjs/asm_v_wasm.cpp:66
```
OS      : Linux ubuntu 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Commit  : ffe4152320b4d72fbfc9c350abda922067ebec01
Version : 112
Build   : cmake .. -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++
```

### Proof of concept

[poc-emscripten-finalize.wasm.txt](https://github.com/WebAssembly/binaryen/files/11003737/poc-emscripten-finalize.wasm.txt)

### Stack dump
```
gdb ./wasm-emscripten-finalize
r ./poc-emscripten-finalize.wasm
```

```
[----------------------------------registers-----------------------------------]
RAX: 0x0
RBX: 0x7ffff6d0bf80 (0x00007ffff6d0bf80)
RCX: 0x7ffff6d5300b (<raise+203>:	mov    rax,QWORD PTR [rsp+0x108])
RDX: 0x0
RSI: 0x7fffffffbe50 --> 0x0
RDI: 0x2
RBP: 0x7ffff6ec8588 ("%s%s%s:%u: %s%sAssertion `%s' failed.\n%n")
RSP: 0x7fffffffbe50 --> 0x0
RIP: 0x7ffff6d5300b (<raise+203>:	mov    rax,QWORD PTR [rsp+0x108])
R8 : 0x0
R9 : 0x7fffffffbe50 --> 0x0
R10: 0x8
R11: 0x246
R12: 0x7ffff7de0de8 ("/origin/binaryen/src/asmjs/asm_v_wasm.cpp")
R13: 0x42 ('B')
R14: 0x7ffff7de0e73 ("!results.isTuple()")
R15: 0x7fffffffc230 ("dynCall_")
EFLAGS: 0x246 (carry PARITY adjust ZERO sign trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x7ffff6d52fff <raise+191>:	mov    edi,0x2
   0x7ffff6d53004 <raise+196>:	mov    eax,0xe
   0x7ffff6d53009 <raise+201>:	syscall
=> 0x7ffff6d5300b <raise+203>:	mov    rax,QWORD PTR [rsp+0x108]
   0x7ffff6d53013 <raise+211>:	xor    rax,QWORD PTR fs:0x28
   0x7ffff6d5301c <raise+220>:	jne    0x7ffff6d53044 <raise+260>
   0x7ffff6d5301e <raise+222>:	mov    eax,r8d
   0x7ffff6d53021 <raise+225>:	add    rsp,0x118
[------------------------------------stack-------------------------------------]
0000| 0x7fffffffbe50 --> 0x0
0008| 0x7fffffffbe58 --> 0x7ffff6daa6d0 (<free>:	endbr64)
0016| 0x7fffffffbe60 --> 0xfbad8000
0024| 0x7fffffffbe68 --> 0x55555559a870 --> 0x555555582b90 --> 0x0
0032| 0x7fffffffbe70 --> 0x55555559a8d5 ("std::string wasm::getSig(wasm::Type, wasm::Type): Assertion `!results.isTuple()' failed.\n")
0040| 0x7fffffffbe78 --> 0x55555559a870 --> 0x555555582b90 --> 0x0
0048| 0x7fffffffbe80 --> 0x55555559a870 --> 0x555555582b90 --> 0x0
0056| 0x7fffffffbe88 --> 0x55555559a92e --> 0x0
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGABRT
0x00007ffff6d5300b in raise () from /lib/x86_64-linux-gnu/libc.so.6
gdb-peda$ bt
#0  0x00007ffff6d5300b in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff6d32859 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff6d32729 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff6d43fd6 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff7c4b2f1 in wasm::getSig[abi:cxx11](wasm::Type, wasm::Type) ()
   from /origin/binaryen/build/bin/../lib/libbinaryen.so
#5  0x00007ffff77f1c1f in wasm::GenerateDynCalls::generateDynCallThunk(wasm::HeapType) ()
   from /origin/binaryen/build/bin/../lib/libbinaryen.so
#6  0x00007ffff77f72d6 in wasm::GenerateDynCalls::visitTable(wasm::Table*) ()
   from /origin/binaryen/build/bin/../lib/libbinaryen.so
#7  0x00007ffff77f3b4b in wasm::Walker<wasm::GenerateDynCalls, wasm::Visitor<wasm::GenerateDynCalls, void> >::doWalkModule(wasm::Module*) () from /origin/binaryen/build/bin/../lib/libbinaryen.so
#8  0x00007ffff77f371d in wasm::WalkerPass<wasm::PostWalker<wasm::GenerateDynCalls, wasm::Visitor<wasm::GenerateDynCalls, void> > >::run(wasm::Module*) () from /origin/binaryen/build/bin/../lib/libbinaryen.so
#9  0x00007ffff76f1670 in wasm::PassRunner::runPass(wasm::Pass*) ()
   from /origin/binaryen/build/bin/../lib/libbinaryen.so
#10 0x00007ffff76f068b in wasm::PassRunner::run() ()
   from /origin/binaryen/build/bin/../lib/libbinaryen.so
#11 0x000055555555ae13 in main ()
#12 0x00007ffff6d34083 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#13 0x000055555555847e in _start ()
```

### Credit

Q1IQ(@Q1IQ)

### PR DESCRIPTION
**Pull request by kripken**
Fixes #5586

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]

File: src/passes/GenerateDynCalls.cpp [hunk 1]
```diff
@@ -118,6 +118,16 @@ static void exportFunction(Module& wasm, Name name, bool must_export) {
...
 void GenerateDynCalls::generateDynCallThunk(HeapType funcType) {
   Signature sig = funcType.getSignature();
+
+  if (sig.results.isTuple()) {
+    // Emscripten output is assumed to be MVP, and not to have multiple return
+    // values. In particular, signatures in Emscripten all look like "abcd"
+    // where "a" is the single return value, and "bcd" are the (in this case
+    // three) parameters.
+    Fatal() << "GenerateDynCalls: Cannot operate on multiple return values:"
+            << sig.results;
```
Comment (sbc100) [inline src/passes/GenerateDynCalls.cpp:128]: Can we not check check for `--enable-mutlivalue` earlier on rather then checking for its usage like this?

Comment (kripken) [reply src/passes/GenerateDynCalls.cpp:128]: Just enabling the feature shouldn't cause an error, I think. It's ok to run `wasm-opt -all` and enable all features, for example. So this PR just checks if the multiple returns part of the multivalue feature is used in practice.

Comment (sbc100) [reply src/passes/GenerateDynCalls.cpp:128]: sgtm
