### PR TITLE
Fix reuse of constant nodes in Precompute

### LINKED ISSUE #2759: Fuzz failure related to "nullref.const nullref"
STR:

```bash
$ bin/wasm-opt testcase.wat -O1 -all --roundtrip
unexpected type
UNREACHABLE executed at /home/azakai/Dev/binaryen/src/wasm/wasm-stack.cpp:695!
Aborted
```

```wat
(module
 (global $global$0 (mut i32) (i32.const 10))
 (export "func_95" (func $0))
 (func $0 (param $0 funcref) (result f64)
  (drop
   (block $label$1 (result nullref)
    (br_if $label$1
     (ref.null)
     (block $label$2 (result i32)
      (global.set $global$0
       (i32.const 1)
      )
      (br_if $label$2
       (i32.const 16958)
       (ref.is_null
        (br_if $label$1
         (ref.null)
         (i32.const -2147483647)
        )
       )
      )
     )
    )
   )
  )
  (f64.const 11)
 )
)
```

Printing it after the `-O1` it has `(nullref.const nullref)` which is invalid I believe.

cc @aheejin 

(Fuzzer ID: 270443532426866051 on binaryen de847689ff78d1a7ab5b28b15bc81874d12ba176 - can also reproduce it using `scripts_fuzz_opt.py ID` with that ID on that commit in binaryen)

### PR DESCRIPTION
**Pull request by aheejin**
Previously we tried to reuse `Const` node if a precomputed value is a
constant node. But now we have two more kinds of constant node
(`RefNull` and `RefFunc`), so we shouldn't reuse them interchangeably,
meaning we shouldn't try to reuse a `Const` node when the value at hand
is a `RefNull`. This correctly checks the type of node and tries to
reuse only if the types of nodes match.

Fixes #2759.

### CODE REVIEW

File: src/passes/Precompute.cpp [hunk 1]
```diff
@@ -174,6 +174,38 @@ struct Precompute
     } while (propagate && worked);
   }
 
+  template<typename T> void reuseConstantNode(T* curr, Flow flow) {
+    if (flow.values.isConcrete()) {
+      // reuse a const / ref.null / ref.func node if there is one
+      if (curr->value && flow.values.size() == 1) {
+        Literal singleValue = flow.getSingleValue();
+        if (curr->value->template is<Const>() && singleValue.type.isNumber()) {
```
Comment (kripken) [inline src/passes/Precompute.cpp:182]: Can do
```
if (singleValue.isNumber()) {
  if (auto* c = curr->value->template dynCast<Const>()) {
    ..
  }
}
```
(to avoid both an `is` and a `cast`) and also later down.

Comment (kripken) [reply src/passes/Precompute.cpp:182]: (and then do an `else if` for the chain)

Comment (aheejin) [reply src/passes/Precompute.cpp:182]: Done.
