### PR TITLE
Aligned allocation fixes. Fixes #1845

### LINKED ISSUE #1845: Debian GNU/Linux: Fails to build on armel, armhf, mips, mipsel, s390x, m68k, alpha and sh4
Hello,

binaryen 61 fails to build from source on different architectures like armel, armhf or mips and mipsel.

You can see the build status here:

https://buildd.debian.org/status/package.php?p=binaryen

It also contains the full build log.

The error seems to be related to alignment:

src/mixed_arena.h:125:43: error: 'new' of type 'MixedArena::Chunk' {aka 'std::aligned_storage<32768, 16>::type'} with extended alignment 16 [-Werror=aligned-new=]
       chunks.push_back(new Chunk[numChunks]);

### PR DESCRIPTION
**Pull request by kripken**
The error in #1845 shows:
```
/<<PKGBUILDDIR>>/src/mixed_arena.h: In member function 'void* MixedArena::allocSpace(size_t, size_t)':
/<<PKGBUILDDIR>>/src/mixed_arena.h:125:43: error: 'new' of type 'MixedArena::Chunk' {aka 'std::aligned_storage<32768, 16>::type'} with extended alignment 16 [-Werror=aligned-new=]
       chunks.push_back(new Chunk[numChunks]);
                                           ^
/<<PKGBUILDDIR>>/src/mixed_arena.h:125:43: note: uses 'void* operator new [](std::size_t)', which does not have an alignment parameter
/<<PKGBUILDDIR>>/src/mixed_arena.h:125:43: note: use '-faligned-new' to enable C++17 over-aligned new support
```
It turns out I had misread the `aligned_storage` docs, and they don't actually do what we need, which is a convenient cross-platform way to do aligned allocation, since `new` itself doesn't support that. Sadly it seems there is no cross-platform way to do it right now, so I added a header in `support` which abstracts over the windows and everything-else ways.

This PR needs help from someone with a windows machine - this compiles on windows, but our CI does not run the code, so this is not tested there.

### CODE REVIEW

File: src/support/alloc.h [hunk 1]
```diff
@@ -0,0 +1,55 @@
+/*
+ * Copyright 2018 WebAssembly Community Group participants
```
Comment (tlively) [inline src/support/alloc.h]: 2019!

**Comment by kripken** [comment]
Updated to 2019.

Still blocking on windows testing as mentioned above - help!

**Comment by kripken** [comment]
To test on windows, I found I can just add some ctest testing, which is pretty easy, and it seems to run ok on the CI here.

Probably we should move more testing and consolidate it with the other tests somehow, but for now this is useful to make sure basics are not broken, which is all we need in this PR.
