### PR TITLE
Fix trapping and dangling insts in memory packing

### LINKED ISSUE #2535: MemoryPacking can result in dangling `data.drop`s
After #2529, it was discovered that MemoryPacking pass does not properly delete or fix `data.drop` instructions (and possibly other instructions like `memory.init`) that refer to deleted segments. Given that #2426 is coming I'm not sure if it's worth fixing per se, but I'll file a bug report here to track this thing.

Test case:
Running
`wasm-opt -all --memory-packing t.wast`

t.wast:
```wast
(module
 (memory 1 1)
 (data (i32.const 0) "")
 (func $bar
  (drop
   (loop (result i32)
    (data.drop 0)
    (i32.const 42)
   )
  )
 )
)
```
results in a validation error saying `[wasm-validator error in function bar] unexpected false: data.drop segment index out of bounds, on, ...`

cc @tlively

### PR DESCRIPTION
**Pull request by aheejin**
This does two things:
- Restore `visitDataDrop` handler deleted in #2529, but now we convert
  invalid `data.drop`s to not `unreachable` but `nop`. This conforms to
  the revised spec that `data.drop` on the active segment can be treated
  as a nop.
- Make `visitMemoryInit` trap if offset or size are not equal to 0 or if
  the dest address is out of bounds. Otherwise drop all its argument.

Fixes #2535.

### CODE REVIEW

File: src/passes/MemoryPacking.cpp [hunk 1]
```diff
@@ -125,20 +125,25 @@ struct MemoryPacking : public Pass {
...
+      Pass* create() override { return new Nullifier; }
 
       void visitMemoryInit(MemoryInit* curr) {
         if (!getModule()->memory.segments[curr->segment].isPassive) {
           Builder builder(*getModule());
           replaceCurrent(builder.blockify(builder.makeDrop(curr->dest),
                                           builder.makeDrop(curr->offset),
-                                          builder.makeDrop(curr->size),
-                                          builder.makeUnreachable()));
+                                          builder.makeDrop(curr->size)));
```
Comment (tlively) [inline src/passes/MemoryPacking.cpp]: This still needs to trap if offset or size are not equal to 0 or if the dest address is out of bounds. I'm actively working on my MemoryPacking patch again, but in the interim changing this code to the following should make the code correct again.

```
          // trap if (dest > memory.size | offset | size) != 0
          replaceCurrent(builder.makeIf(
            builder.makeBinary(
              OrInt32,
              builder.makeBinary(
                GtUInt32, curr->dest, builder.makeHost(MemorySize, Name(), {})),
              builder.makeBinary(OrInt32, curr->offset, curr->size)),
            builder.makeUnreachable()));
```

Comment (aheejin) [reply src/passes/MemoryPacking.cpp]: Thanks!
