### PR TITLE
Ordering bug fixes for windows

### LINKED ISSUE #692: module[0]->str() == MODULE
I tried to build the binaries from source in master branch with handcrafted batch script, no warning and error during compilation. But when I tried to run `asm2wasm -h`, I got assertion failed:

```
Assertion failed!

Program: C:\Users\jie\Downloads\binaryen-master\asm2wasm.exe
File: src/wasm-s-parser.h, Line 273

Expression: module[0]->str() == MODULE

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

The same applies to all other binaries regardless of what command arguments I used.

I am using mingw64 gcc 5.4.0 (posix thread model).

**Note that I have no trouble building and running release version_11 with the (almost) same configuration!**

gdb:
```
C:\Users\jie\Downloads\binaryen-master>gdb --args ./asm2wasm -h
GNU gdb (GDB) 7.10.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./asm2wasm...done.
(gdb) break wasm::SExpressionWasmBuilder::SExpressionWasmBuilder
Breakpoint 1 at 0x470936: file src/wasm-s-parser.h, line 272.
(gdb) run
Starting program: C:\Users\jie\Downloads\binaryen-master\asm2wasm.exe -h
[New Thread 4456.0x714]
[New Thread 4456.0xc20]
[New Thread 4456.0x5a8]
[New Thread 4456.0x380]

Breakpoint 1, wasm::SExpressionWasmBuilder::SExpressionWasmBuilder (
    this=0x263fc70, wasm=..., module=...) at src/wasm-s-parser.h:272
272       SExpressionWasmBuilder(Module& wasm, Element& module) : wasm(wasm), al
locator(wasm.allocator), importCounter(0), globalCounter(0) {
(gdb) print module[0]->str()
$1 = {str = 0x2653dc0 "module"}
(gdb) print MODULE
$2 = {<cashew::IString> = {str = 0x0}, <No data fields>}
(gdb) kill
Kill the program being debugged? (y or n) y
(gdb) quit
```

The batch script:
```
@echo off
cd C:\Users\jie\Downloads\binaryen-master

echo Set up env...
set cxx=g++
set flag=-std=c++11 -Isrc -O0 -g3 -D_GNU_SOURCE -msse2 -mfpmath=sse -fno-omit-frame-pointer -Wall -Wextra -Wno-unused-parameter
set compile=%cxx% %flag% -c
set build=%cxx% %flag%

rem goto skip
echo Compile asmjs...
%compile% src/asmjs/asm_v_wasm.cpp
%compile% src/asmjs/shared-constants.cpp
ar rcs libasmjs.a *.o
del *.o

echo Compile emscripten...
%compile% src/emscripten-optimizer/optimizer-shared.cpp
%compile% src/emscripten-optimizer/parser.cpp
%compile% src/emscripten-optimizer/simple_ast.cpp
ar rcs libemscripten.a *.o
del *.o

echo Compile passes...
%compile% src/passes/pass.cpp
%compile% src/passes/CoalesceLocals.cpp
%compile% src/passes/DeadCodeElimination.cpp
%compile% src/passes/DropReturnValues.cpp
%compile% src/passes/DuplicateFunctionElimination.cpp
%compile% src/passes/LowerIfElse.cpp
%compile% src/passes/MergeBlocks.cpp
%compile% src/passes/Metrics.cpp
%compile% src/passes/NameManager.cpp
%compile% src/passes/NameList.cpp
%compile% src/passes/OptimizeInstructions.cpp
%compile% src/passes/PostEmscripten.cpp
%compile% src/passes/Precompute.cpp
%compile% src/passes/Print.cpp
%compile% src/passes/RemoveImports.cpp
%compile% src/passes/RemoveMemory.cpp
%compile% src/passes/RemoveUnusedBrs.cpp
%compile% src/passes/RemoveUnusedNames.cpp
%compile% src/passes/RemoveUnusedFunctions.cpp
%compile% src/passes/ReorderLocals.cpp
%compile% src/passes/ReorderFunctions.cpp
%compile% src/passes/SimplifyLocals.cpp
%compile% src/passes/Vacuum.cpp
ar rcs libpasses.a *.o
del *.o

echo Compile support...
%compile% src/support/archive.cpp
%compile% src/support/bits.cpp
%compile% src/support/colors.cpp
%compile% src/support/command-line.cpp
%compile% src/support/file.cpp
%compile% src/support/safe_integer.cpp
%compile% src/support/threads.cpp
ar rcs libsupport.a *.o
del *.o

echo Building wasm-shell...
%build% -o wasm-shell src/tools/wasm-shell.cpp src/wasm.cpp -L. -lasmjs -lemscripten -lpasses -lsupport

echo Building wasm-opt...
%build% -o wasm-opt src/tools/wasm-opt.cpp src/wasm.cpp -L. -lasmjs -lemscripten -lpasses -lsupport

echo Building asm2wasm...
%build% -o asm2wasm src/tools/asm2wasm.cpp src/wasm.cpp -L. -lasmjs -lemscripten -lpasses -lsupport

echo Building s2wasm...
%build% -o s2wasm src/tools/s2wasm.cpp src/wasm-linker.cpp src/wasm.cpp -L. -lasmjs -lpasses -lsupport

echo Building wasm-as...
%build% -o wasm-as src/tools/wasm-as.cpp src/wasm.cpp -L. -lasmjs -lpasses -lsupport

echo Building wasm-dis...
%build% -o wasm-dis src/tools/wasm-dis.cpp src/wasm.cpp -L. -lpasses -lsupport -lasmjs

dir /b *.exe
```

### PR DESCRIPTION
**Pull request by kripken**
First commit fixes call order being unspecified over `|`.

Second fixes #692, where we relied on the order of global ctors.

### CODE REVIEW

**Comment by kripken** [comment]
Looks like no concerns, merging since I've gotten reports of people hitting these issues. If there are comments later we can address them in followups.

File: src/passes/OptimizeInstructions.cpp [hunk 1]
```diff
@@ -71,7 +72,16 @@ struct PatternDatabase {
...
 
-static PatternDatabase database;
+static PatternDatabase* database = nullptr;
+
+static void ensureDatabase() {
+  if (!database) {
+    // we must only ever create one database
+    static OnlyOnce onlyOnce;
+    onlyOnce.verify();
+    database = new PatternDatabase;
```
Comment (jfbastien) [inline src/passes/OptimizeInstructions.cpp]: You don't need this only once thing since function static vars are guaranteed to be safely initialized once, on first call, even if there are threads. You can just have static PatternDatabase *database = new PatternDatabase;

Comment (jfbastien) [inline src/passes/OptimizeInstructions.cpp]: And then the function is getDatabase() and returns that static value. No global.

Comment (kripken) [inline src/passes/OptimizeInstructions.cpp]: Almost, yeah, but to thread-safely initialize the static variable once, it would take a lock, wouldn't it? This code avoids that (by relying on the fact that we'll reach this on the main thread first).

Comment (jfbastien) [inline src/passes/OptimizeInstructions.cpp]: It can be an atomic operation. I'd use what the language provides unless this benchmarks as a performance problem.

Comment (kripken) [inline src/passes/OptimizeInstructions.cpp]: Yeah, maybe you're right. But since this `database` is I am guessing hot, we should measure first.
