### PR TITLE
Handle module name collisions in MinifyImportsAndExports using a new output format

### LINKED ISSUE #8203: MinifyImportsAndExports fails on duplicate names.
When running the minification pass with --minify-imports-and-exports-and-modules, the pass will fail with the following assertion:

```
Assertion failed: (res.second), function operator(), file MinifyImportsAndExports.cpp, line 118.
[1]    5104 abort      wasm-opt opt.wasm --enable-reference-types --enable-gc --enable-bulk-memory
```

This appears to be because the pass does not deal well with duplicate names, even if they come from different modules. In fact, duplicate imports even with the same module and name is explicitly allowed by the WebAssembly specification.

### PR DESCRIPTION
**Pull request by kripken**
Before we just minified the basename, ignoring the module name entirely. That
meant we errored if two modules had the same basename,

```wat
(import "A" "foo" ..)
(import "B" "foo" ..)
```

Fix this by tracking module names alongside base names.

The output format must change to support this, as we need to print out the
module name as well. While making a breaking change here, change the
output to JSON which will handle escaping properly, and is more structured
and explicit.

Fixes #8203

Needs a corresponding Emscripten change to parse the new output format.

### CODE REVIEW

File: src/passes/MinifyImportsAndExports.cpp [hunk 1]
```diff
@@ -93,10 +99,40 @@ struct MinifyImportsAndExports : public Pass {
...
+        } else {
+          std::cout << ',';
+        }
+        std::cout << "\n  [";
+        String::printEscaped(std::cout, key.second.str) << ", ";
+        String::printEscaped(std::cout, new_.str) << "]";
+      }
     }
+    std::cout << "\n ]\n";
+    std::cout << "}\n";
```
Comment (sbc100) [inline src/passes/MinifyImportsAndExports.cpp:135]: Does binaryen write json elsewhere?    If so mabye we can make utilities for dumping this kind of data?

**Review by sbc100 — APPROVED** [review]

File: src/passes/MinifyImportsAndExports.cpp (hunk 1 above)
Comment (kripken) [reply src/passes/MinifyImportsAndExports.cpp:135]: We also write it from metadce. Perhaps some kind of utility makes sense to consider - we do have one for JSON reading of wtf16, but not writing and not utf8.
