### PR TITLE
Fixup block-nested pops even when EH is not enabled

### LINKED ISSUE #7127: [Old EH] "pop's location is not valid"-error since Emscripten 3.1.73
Since Emscripten 3.1.73 (https://chromium.googlesource.com/emscripten-releases/+/b363a83) I encounter errors similar to those described in #6918 when attempting to print the target features section of an already built Wasm binary.

For example:
```console
$ $EMSDK/upstream/bin/wasm-opt --mvp-features --print-features -o /dev/null vips.wasm | sed 's/^--enable-//' | paste -sd' '
...
[wasm-validator error in function 3998] unexpected false: , on 
(try
 (do
  (local.set $0
   (call $3
    (local.get $0)
   )
  )
 )
 (catch $eimport$1
  (drop
   (call $354
    (block (result i32)
     (local.set $2
      (pop i32)
     )
     (global.set $gimport$1
      (local.get $1)
     )
     (local.get $2)
    )
   )
  )
  (call $295)
  (local.set $0
   (i32.const 0)
  )
 )
)
catch's body (eimport$1)'s pop's location is not validFatal: error validating input
```

However, with Emscripten 3.1.72, these errors do not occur for the same Wasm binary:
```console
$ $EMSDK/upstream/bin/wasm-opt --mvp-features --print-features -o /dev/null vips.wasm | sed 's/^--enable-//' | paste -sd' '
threads mutable-globals nontrapping-float-to-int simd bulk-memory sign-ext exception-handling reference-types multivalue
```

This indicates a possible(?) regression in this revision range:
https://github.com/WebAssembly/binaryen/compare/69591de...b1c5a00

The Wasm binary in question is relatively large (~5.4 MiB) and is available for download here:
[reproducer.zip](https://github.com/user-attachments/files/17960246/reproducer.zip)

Alternatively, you can reproduce this issue using:
```console
$ git clone https://github.com/kleisauke/wasm-vips.git
$ cd wasm-vips/
$ npm run build -- --enable-wasm-eh
```

### PR DESCRIPTION
**Pull request by tlively**
While parsing a binary file, there may be pops that need to be fixed up
even if EH is not (yet) enabled because the target features section has
not been parsed yet. Previously `EHUtils::handleBlockNestedPops` did not
do anything if EH was not enabled, so the binary parser would fail to
fix up pops in that case. Add an optional parameter to override this
behavior so the parser can fix up pops unconditionally.

Fixes #7127.

### CODE REVIEW

File: src/ir/eh-utils.cpp [hunk 1]
```diff
@@ -149,9 +149,6 @@ void handleBlockNestedPop(Try* try_, Function* func, Module& wasm) {
 }
 
 void handleBlockNestedPops(Function* func, Module& wasm) {
-  if (!wasm.features.hasExceptionHandling()) {
-    return;
-  }
```
Comment (kripken) [inline src/ir/eh-utils.cpp:154]: I worry this is a significant regression. Before this PR, many passes would skip this pop handling in e.g. normal Emscripten output, just because the feature was not present. That is, this fixes parsing, but it is slowing down optimizations IIUC.

If the parsing issue is that we haven't seen the features section yet, perhaps we can fix that by doing what we now do with names - scan ahead for the features section first?

Comment (kripken) [reply src/ir/eh-utils.cpp:154]: We can do the check in those passes too, as the code here does, I guess - but if that's the best option, perhaps we can avoid the code duplication by adding `handleBlockNestedPopsAfterParse` (or a much better name hopefully) that does the feature check?

Comment (tlively) [reply src/ir/eh-utils.cpp:154]: What do you think about adding an extra optional parameter `bool ignoreFeatures = false` that would only be used by the parser code?

Comment (kripken) [reply src/ir/eh-utils.cpp:154]: Sounds good. Maybe an enum?

**Comment by tlively** [comment]
Done!

File: test/lit/binary/stacky-eh-legacy.test [hunk 2]
```diff
@@ -35,15 +35,15 @@
 ;; The fixup will hoist the 'pop' and create another local to store it right
 ;; after 'catch'.
 
-;; RUN: wasm-opt -all %s.wasm -S -o - | filecheck %s
+;; RUN: wasm-opt %s.wasm -S -o - | filecheck %s
```
Comment (kripken) [inline test/lit/binary/stacky-eh-legacy.test:38]: How does this command not error in the validator, as the wasm uses EH?

**Review by kripken — APPROVED** [review]

File: test/lit/binary/stacky-eh-legacy.test (hunk 2 above)
Comment (kripken) [reply test/lit/binary/stacky-eh-legacy.test:38]: Oh, the features section? Which is the binary change I guess.

Comment (tlively) [reply test/lit/binary/stacky-eh-legacy.test:38]: I added a target features section enabling EH to the binary, so this test now reflects what happens in practice when Emscripten first parses a binary.
