### PR TITLE
Avoid __popcnt and __popcnt64 intrinsics for MSC

### LINKED ISSUE #2942: Misoptimization causing a runtime panic in Rust code
In the archive - [coreutils.nodbg.zip](https://github.com/WebAssembly/binaryen/files/4873511/coreutils.nodbg.zip) - you will find two files, `coreutils.nodbg.wasm` and `coreutils.nodbg.opt.wasm`.

Unfortunately, they're fairly large, but that's as far as I could get for now. Maybe you'll be able to reduce them further and get to the bottom of the issue with `wasm-reduce`, but I couldn't spend more time on it.

Initially I've built the original source code in a release mode, which, combined with `wasm-opt --asyncify -Os`, introduced an infinite loop in the resulting WebAssembly, and I couldn't figure out what's going on.

After rebuilding in debug mode, I'm getting a [slightly more helpful] runtime assertion panic somewhere in initialisation of the app (when it tries to allocate data for a `HashMap`), and that panic is not reproducible by the original app, suggesting that some values were indeed misoptimized.

My initial assumption was that this is some bug specific to Asyncify, but, by slowly eliminating different options, got down to just `-O1`.

`coreutils.nodbg.opt.wasm` is produced with

```bash
$ wasm-opt.exe coreutils.nodbg.wasm -O1 -g -o coreutils.nodbg.opt.wasm
```

using `wasm-opt` from the latest commit on `master` (https://github.com/WebAssembly/binaryen/commit/cd0cc95e2794375c463a69833b1ccc9cc96d597c), however I could reproduce the issue with older versions as well - should be easy to do so using the command above.

To reproduce the issue, install a WASI-compatible runner, e.g. Wasmtime or Wasmer, and invoke it on both Wasm files.

This is what I'm seeing on the unoptimised file:

```
$ wasmtime -g coreutils.nodbg.wasm
coreutils.nodbg 0.0.1 (multi-call binary)

Usage: coreutils.nodbg [function [arguments...]]

Currently defined functions/utilities:

    base32, base64, basename, cat, cksum, comm, cp, cut, date, df,
    dircolors, dirname, echo, env, expand, expr, factor, false, fmt, fold,
    hashsum, head, join, link, ln, ls, md5sum, mkdir, mktemp, more, mv, nl,
    od, paste, printenv, printf, ptx, pwd, readlink, realpath, relpath, rm,
    rmdir, seq, sha1sum, sha224sum, sha256sum, sha3-224sum, sha3-256sum,
    sha3-384sum, sha3-512sum, sha384sum, sha3sum, sha512sum, shake128sum,
    shake256sum, shred, shuf, sleep, sort, split, sum, tac, tail, tee, test,
    tr, true, truncate, tsort, unexpand, uniq, wc, yes
```

and the optimised one:

```
$ wasmtime -g coreutils.nodbg.opt.wasm
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LayoutErr { private: () }', C:\Users\rreverser\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\src/libcore/alloc/layout.rs:231:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: failed to run main module `coreutils.nodbg.opt.wasm`

Caused by:
    0: failed to invoke command default
    1: wasm trap: unreachable
       wasm backtrace:
         0: 0x55cdd9 - <unknown>!__rust_start_panic
         1: 0x55bf3e - <unknown>!rust_panic
         2: 0x55bc75 - <unknown>!std::panicking::rust_panic_with_hook::hb8132b4308a71007
         3: 0x55baca - <unknown>!rust_begin_unwind
         4: 0x568654 - <unknown>!core::panicking::panic_fmt::hdd2ab611a748a491
         5: 0x56d5ae - <unknown>!core::option::expect_none_failed::habae0dd01495a6a7
         6: 0x339708 - <unknown>!core::result::Result<T,E>::unwrap::h0b29ccc7c9c10d07
         7: 0x89b8 - <unknown>!core::alloc::layout::Layout::pad_to_align::hae1edfd09d682fcc
         8: 0x5db74 - <unknown>!core::alloc::layout::Layout::array::h630440cfaca600e0
         9: 0x57b73 - <unknown>!hashbrown::raw::calculate_layout::h32a6c9dc2acba081
         10: 0x594fe - <unknown>!hashbrown::raw::RawTable<T>::new_uninitialized::h92067dc36e22c506
         11: 0x59b10 - <unknown>!hashbrown::raw::RawTable<T>::try_with_capacity::h64ecb1c3ee6c48f1
         12: 0x5864c - <unknown>!hashbrown::raw::RawTable<T>::resize::h1c5680148fe8f2d3
         13: 0x58216 - <unknown>!hashbrown::raw::RawTable<T>::reserve_rehash::h36d80382ea8e9ffc
         14: 0x5a96b - <unknown>!hashbrown::raw::RawTable<T>::reserve::h96e5457f885fde23
         15: 0x5a872 - <unknown>!hashbrown::raw::RawTable<T>::insert::hd555411ed0fee9f1
         16: 0x77f8e - <unknown>!hashbrown::map::HashMap<K,V,S>::insert::h263136bf7b5163b1
         17: 0x44e23 - <unknown>!std::collections::hash::map::HashMap<K,V,S>::insert::h659bd993b5cd211f
         18: 0xe449 - <unknown>!coreutils::util_map::h81ccd6dc74a16eac
         19: 0x7d64 - <unknown>!coreutils::main::h791587a0c1680f0e
         20: 0x4cd5c - <unknown>!std::rt::lang_start::{{closure}}::h14ee8eacd196f15d
         21: 0x55aa3b - <unknown>!std::sys_common::backtrace::__rust_begin_short_backtrace::hd2bb8386068f691a
         22: 0x55c02a - <unknown>!std::rt::lang_start_internal::h66de5b0ec01e6d33
         23: 0x4cd33 - <unknown>!std::rt::lang_start::h01445dbe67544740
         24: 0x849f - <unknown>!__original_main
         25: 0x7cad - <unknown>!_start

```

### PR DESCRIPTION
**Pull request by MaxGraey**
Potentially fix #2942

### CODE REVIEW

**Comment by kripken** [comment]
1. @RReverser perhaps you can check if this fixes that issue?

2. But why do we think this might be the issue - is there a reason to suspect these intrinsics are broken on msvc?

**Comment by MaxGraey** [comment]
> But why do we think this might be the issue - is there a reason to suspect these intrinsics are broken on msvc?

Some of intrinsics like `__popcnt` or `__lzcnt` on MSC required cpuid check before usage. It's just direct asm injection I guess without any fallbacks. But with `_BitScanForward` / `_BitScanReverse` we have different story and that's instructions should be hardware independent)

File: src/ir/bits.h [hunk 1]
```diff
@@ -45,7 +45,7 @@ struct Bits {
     }
     // otherwise, see if adding one turns this into a 1-bit thing, 00011111 + 1
     // => 00100000
-    if (PopCount(mask + 1) != 1) {
+    if (mask & (mask + 1)) {
```
Comment (MaxGraey) [inline src/ir/bits.h:48]: `mask & (mask + 1)` is not fully equivalent of `PopCount(mask + 1) != 1` because not handle case when `mask == uint32_t(-1)` but this already checked [earlier](https://github.com/WebAssembly/binaryen/pull/2944/files#diff-58b7cf13906e9b5a4ba6306aaea394aaL40) so we cant use more simplify version without this special case here

Comment (tlively) [reply src/ir/bits.h:48]: Makes sense to me. It would be good to fix the comment to reflect the new calculation, since it currently suggests that we are using popcount.

**Comment by kripken** [comment]
Sounds good, let's merge this then.

@RReverser if you get a chance, it would still be good to confirm if this fixes that issue.

**Comment by RReverser** [comment]
@kripken I already mentioned on the original issue that I tried it and it didn't change anything for me (neither size nor the reproduction): https://github.com/WebAssembly/binaryen/issues/2942#issuecomment-654157125

**Comment by kripken** [comment]
Got it, thanks @RReverser
